[[VaadinFlowComponents]]
== Vaadin Flow UI components

The `holon-vaadin-flow` artifact is the main entry point to enable the Holon platform Vaadin Flow integration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow</artifactId>
<version>{revnumber}</version>
----

It provides integration between the Vaadin Flow core architecture and the Holon Platform one, providing also a set of UI components specifically designed to ensure a seamless integration with the Holon Platform Property model, Datastore API, authentication and internationalization APIs.

[[DatastoreIntegration]]
=== Datastore API integration

The Holon Platform link:holon-core.html#Datastore[Datastore API^] can be used to bind a UI component to backend data in a simple and powerful way, relying on the Holon Platform link:holon-core.html#Property[Property model^] to represent the underlying data model.

The link:{apidir}/com/holonplatform/vaadin/flow/data/DatastoreDataProvider.html[DatastoreDataProvider^] API is a standard Vaadin Flow `com.vaadin.flow.data.provider.DataProvider` which uses the `Datastore` API to fetch data from backend and makes available a set of configuration methods to control and setup the queries to perform.

Since it is a standard `DataProvider`, it can be seamlessy used in any Vaadin UI component which support data binding.

The `DatastoreDataProvider` provides a set of `create(..)` and `builder(..)` methods to build and configure a new `Datastore` based `DataProvider`. At least the following elements are required to create a `DatastoreDataProvider`:

* The reference to the `Datastore` instance to use.
* A `DataTarget` declaration, which represents the data model _entity_ to use as data source (for example, a RDBMS table name).

==== Item types

By default, the Holon Platform link:holon-core.html#Property[Property model^] is used to represent the backend data model attributes, and the link:holon-core.html#PropertyBox[PropertyBox^] type to represent a data source _item_, intended as a collection of properties and their values.

So, besides the `Datastore` reference and the `DataTarget` definition, the *property set* to use has to be provided to the `DatastoreDataProvider` builder methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider1,indent=0]
----
<1> Property set declaration
<2> Data target definition
<3> Datastore reference
<4> Create a new `DatastoreDataProvider` using the `SUBJECT` property set
<5> Create a new `DatastoreDataProvider` providing the `ID` and `NAME` properties as property set

Furthermore, the `DatastoreDataProvider` API provides methods to use a *bean class* as item type. The item property set is obtained form the bean class attributes, using the bean property names as property set property names.

TIP: See the link:holon-core.html#Beans[Java Beans and property model^] documentation section for information about the conventions and the configuration options which can be used when a Java Bean is used with the Holon Platform property model.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider2,indent=0]
----
<1> Data target definition
<2> Datastore reference
<3> Create a new `DatastoreDataProvider` using the `MyBean` class as item type

==== Filter types

By default, the `QueryFilter` type is used used as data provider filter type, since it is the default property model representation for the `Datastore` API query restrictions definition.

To use a different data provider filter type, a *filter converter function* can be configured for the `DatastoreDataProvider`, to provide the custom filter type to `QueryFilter` type conversion logic.

In the example below, a `String` type filter is used and the conversion function creates a `QueryFilter` which represents the condition "The `NAME` data model attribute value starts with the given filter value":

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider3,indent=0]
----

Similarly when a bean item type is used:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider4,indent=0]
----

==== Custom item and filter type

The `DatastoreDataProvider` API makes also available methods to customize both the item type and the data provider filter type, providing:

* The `PropertyBox` type to the custom item type conversion function.
* The custom filter type to the `QueryFilter` type conversion function.

For example, using a `MyItem` item class and a `String` filter type:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider5,indent=0]
----
<1> The `SUBJECT` property set is used as query projection
<2> Item conversion function: from the `PropertyBox` type object to the `MyItem` item type
<3> Filter conversion function: from a `String` type filter to a `QueryFilter` type

[[DatastoreQueryConfiguration]]
==== `Datastore` Query configuration

The queries performed by the `Datastore` to fetch the data from backend can be configured using the `DatastoreDataProvider` *builder API*.

===== Query filters and sorts

The query filters and sorts can be configured in two ways:

*1. At construction time, using the appropriate builder methods:* 

The `DatastoreDataProvider` builder API provide methods to:

* Add one or more `QueryFilter` to the query definition. These filters will always be included in the query execution.
* Add one or more `QuerySort` to the query definition. These sorts will always be included in the query execution.
* Set a default `QuerySort`, which will be used when no other sort is configured for the query.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider6,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a query filter
<3> Add a query sort
<4> Set the default query sort

*2. Dynamically, using a `QueryConfigurationProvider`:* 

One or more `QueryConfigurationProvider` references can be configured for the query using the `DatastoreDataProvider` builder API. 

At each query execution, the `getQueryFilter()` and `getQuerySort()` methods of each available `QueryConfigurationProvider` will be invoked to obtain the filters and sorts to add to the query, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider7,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a `QueryConfigurationProvider`
<3> At each query execution, this method will be invoked to obtain the query filters, if any
<4> At each query execution, this method will be invoked to obtain the query sorts, if any

===== `QuerySortOrder` conversion

When the standard Vaadin Flow `com.vaadin.flow.data.provider.QuerySortOrder` type is used for the data provider query configuration, the `DatastoreDataProvider` can be configured to control how a `QuerySortOrder` declaration is converted into a `QuerySort` definition.

For this purpose, the `DatastoreDataProvider` builder API allows to configure a `QuerySortOrder` conversion function.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider8,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Set the `QuerySortOrder` conversion function

===== Item identifier

By default, the item itself is used as _item identifier_ to discern each item from another within the query results. The item identification relies on the standard Java `equals` and `hashCode` object methods.

When a `PropertyBox` type item is used, the default item identification strategy relies on the property set *identifier properties* values, if declared.

TIP: See the link:holon-core.html#IdentifierProperties[Identifier properties^] documentation section for details.

If a custom item identifier should be used, an item identifier provider function can be configured using the `DatastoreDataProvider` builder API. This function must provide the item identifier for each item obtained form query execution.

.Example using a PropertyBox type item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider9,indent=0]
----
<1> Set an item identifier provider function which provides the `ID` property value as item identifier

.Example using a bean item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider10,indent=0]
----
<1> Set an item identifier provider function which provides the bean id value as item identifier using the `getId()` method

==== Setup a `Datastore` data provider using builders

The Holon Platform Vaadin Flow module _builder_ APIs provides covenient methods to setup a `Datastore` based data provider for UI components which support data binding.

Example for a _single select_, implemented using a Vaadin `ComboBox` component:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=builder,indent=0]
----

See <<Components>> to learn about the available component builders.

[[I18n]]
=== Internationalization

The Holon Platform Vaadin Flow module provides a complete integration with the Holon Platform link:holon-core.html#i18n[internationalization^] architecture, making UI components and messages localization simple and conistent with the full application stack.

Each localizable messages is represented by:

* A required *message code*, i.e. the `String` key to be used to obtain the message localization for a given `Locale`.
* An optional *default message*, to be used if a localized message is not available for a `Locale`.
* A set of optional *localization arguments*, which can be used to replace a specific _placeholder_ with the actual values.

The localizable message attributes described above can be declared and represented using the link:{coreapidir}/com/holonplatform/core/i18n/Localizable.html[Localizable^] interface, which provides convenient methods to create `Localizable` instances providing the message localization attributes.

The UI component builders which allow to setup localizable messages and texts, always support the `Localizable` API to provide the message localization attributes, providing also convenient methods to directly set the message localization attributes.

Example using a _button_ component builder:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=builder1,indent=0]
----
<1> Set the button text using a not localizable message
<2> Set the button text using a localizable message, providing the default message and the localization code
<3> Set the button text using a localizable message, also providing two message localization arguments 
<4> Set the button text using a `Localizable` reference

See <<Components>> to learn about the available component builders.

==== LocalizationContext and LocalizationProvider

The Holon Platform internationalization support relies on the link:holon-core.html#LocalizationContext[LocalizationContext^] API, which acts as message resolver, localized data formatter and holder for the current user `Locale`.

In order for the UI components localization to work, one of the following conditions must be met:

* A `LocalizationContext` is available as _context_ resource and a `Locale` is configured. See the Holon Platform link:holon-core.html#Context[Context^] architecture for information about the context resources management.

* Otherwise, a Vaadin Flow `I18NProvider` is available from the current Vaadin Service.

TIP: See <<VaadinSessionScope>> to learn about the _context scope_ for resources bound to the current Vaadin application session.

The link:{apidir}/com/holonplatform/vaadin/flow/i18n/LocalizationProvider.html[LocalizationProvider^] API is used by the UI components and builders to obtain the localization information and to localize the messages to display.

The `LocalizationProvider` API makes available a set of static methods to seamlessy integrate the messages localization in any part of the application, delegating the actual internationalization logic to the concrete localization provider, if available, which can be either a Holon Platform `LocalizationContext` or a Vaadin Flow `I18NProvider`.

The *actual localization service to use* is automatically detected with the following strategy:

* If a Vaadin Flow `I18NProvider` is available from current `VaadinService`, it is used for messages localization.
* Otherwise, a `LocalizationContext` is used if available as a _context_ resource.

This way, the `LocalizationProvider` API  `getLocalization` static methods can be used as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=localizationProvider1,indent=0]
----
<1> Get the localization for the given `Localizable` message using the given `Locale`
<2> Get the localization for the given `message.localization.code` message code using the given `Locale` and the default `Default message` message if the localization is not available

If the `Locale` is not explicitly provided, the `LocalizationProvider` API  `localize` static methods can be used and the *current Locale* is obtained with the following strategy:

* If a current `UI` is available and a `Locale` is configured for the `UI`, this one is used.
* If a `LocalizationContext` is available as a _context_ resource and it is localized, the `LocalizationContext` current `Locale` is used.
* If a Vaadin Flow `I18NProvider` is available from current `VaadinService`, the first provided `Locale` is used if available.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=localizationProvider2,indent=0]
----
<1> Get the current `Locale`, if available
<2> Get the localization for the given `Localizable` message using the current `Locale`
<3> Get the localization for the given `message.localization.code` message code using the current `Locale`: the default `Default message` message is returned if the message localization or the current `Locale` is not available

==== Use a LocalizationContext as I18NProvider

The Holon Platform `LocalizationContext` can be used as a standard Vaadin Flow `I18NProvider` through the link:{apidir}/com/holonplatform/vaadin/flow/i18n/LocalizationContextI18NProvider.html[LocalizationContextI18NProvider^] API.

TIP: See the link:holon-core.html#LocalizationContext[LocalizationContext^] documentation for information about the `LocalizationContext` configuration and use.

The `LocalizationContextI18NProvider` provides static methods to build a `I18NProvider` instance which uses a `LocalizationContext` as message localizations provider.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=i18nprovider1,indent=0]
----
<1> Set the messages localization source
<2> Set the initial `Locale`
<3> Create a `I18NProvider` instance using the `LocalizationContext` as message localization provider

A `LocalizationContextI18NProvider` which uses the current `LocalizationContext` (if available as a _context_ resource) can be obtained with the `create()` method:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=i18nprovider2,indent=0]
----
<1> Create a `LocalizationContext`
<2> Put the `LocalizationContext` instance as a Vaadin Session attribute
<3> Create a `I18NProvider` instance which uses the current `LocalizationContext`

[[HasComponent]]
=== The `HasComponent` interface

Many of the additional UI components provided by the Holon Platform Vaadin Flow module extends the link:{apidir}/com/holonplatform/vaadin/flow/components/HasComponent.html[HasComponent^] interface to make available the actual Vaadin `com.vaadin.flow.component.Component` which can be used in the application UI. 

The `getComponent()` method should be used to obtain the actual `Component`, for example to add it to a layout.

This because all the Holon UI components are represented using an _interface_, while the Vaadin `Component` object is a _class_. For this reason, the UI component interface cannot directly extend a class and the actual Vaadin `Component` is thus provided through the `getComponent()` method.

Example for an `Input` type component:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=hascomponent,indent=0]
----
<1> Create a String type `Input`
<2> Use the `getComponent()` method to add the actual input component to a layout

All the Holon UI components interfaces are located in the `com.holonplatform.vaadin.flow.components` package.

Furthermore, the `HasComponent` API provides methods to check if the actual component supports a set of features and to obtain the appropriate interface which allow to manage a specific feature. 

Some of the component features which can be checked and accessed are:

* _Enabled mode_: using `hasEnabled()`.
* _Size_: using `hasSize()`.
* _Style_: using `hasStyle()`.
* _Label_: using `hasLabel()`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=hascomponent2,indent=0]
----
<1> Create a String type `Input`
<2> Check if the component supports the enabled mode and if so set it to `false`
<3> Check if the component supports size and if so set it to full
<3> Check if the component supports style and if so add a CSS style class name
<4> Check if the component supports a label and if so set it to `My label`

[[Components]]
=== Component builders and providers

The link:{apidir}/com/holonplatform/vaadin/flow/components/Components.html[Components^] API is *the main entry point* to build and configure the UI components.

It provides a complete set of methods to obtain _fluent_ builders to create and configure both standard Vaadin Flow components and the additional UI components provided by the Holon Platform Vaadin Flow module.

The `Components` API structure:

|===
|Sub-interface |Provides

|*[NONE]*
|A set of _configure(*)_ methods to setup existing standard component instances and a set of methods to obtain the _fluent_ builders for base Vaadin components, such as `Button` and standard layout components. See <<BaseBuilders>>.

|*dialog*
|Message and question dialogs builders. See <<Dialogs>>.

|*view*
|Builders for view components and forms. See <<View>>.

|*input*
|Builders input components and forms. See <<Input>>.

|*listing*
|Builders for grid type components to list data. See <<Listing>>.
|===

==== Component builders structure

Each component builder API is composed by a set of specific builders, each related to a specific feature of the component. The feature builders are independent from the specific UI component to build, thus providing a common API which makes component configuration simple and intuitive.

For example, the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasTextConfigurator.html[HasTextConfigurator^] represents a builder part for UI components which supports a _text_, and it is included in any builder for UI components with text support.

Similarly, the the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasSizeConfigurator.html[HasSizeConfigurator^] API is included in component builders which supports the component _size_ configuration.

This ensures a consistent and common API to build and configure any UI component.

In the example below, the `HasTextConfigurator` and the `HasSizeConfigurator` are used in the same way to configure a _label_ and a _button_ component text and size:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=builders1,indent=0]
----
<1> Get a _label_ component builder
<2> Set the label text (using the `HasTextConfigurator` API)
<3> Set the label width (using the `HasSizeConfigurator` API)
<4> Get a _button_ component builder
<5> Set the button text (using the `HasTextConfigurator` API)
<6> Set the button width (using the `HasSizeConfigurator` API)

[[BaseBuilders]]
==== Base components builders

===== Button

The `Components.button()` method provides a standard Vaadin `Button` component builder, with localizable text support.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=button,indent=0]
----
<1> Get the `Button` builder
<2> Set the button text
<3> Set the button localizable text, providing a default text and a message localization code
<4> Set the button description
<5> Set the button width to 100%
<6> Add a CSS style class name
<7> Add a theme variant
<8> Set the button icon
<9> Automatically disables button when clicked
<10> Add a click event listener
<11> Shorter to directly create a `Button` providing the text and the click handler

The `Components.nativeButton()` builder can be used to build a `NativeButton` component.

===== Label

A _label_ component can be used to display a text, which can be *localizable*, and can be implemented using a set of tags. The default tag used by the `Components.label()` method is `DIV`.

TIP: See <<I18n>> for information about the UI components text localization.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=label1,indent=0]
----
<1> Get a label builder using a `Div` component
<2> Set the label text
<3> Set the label localizable text, providing a default text and a message localization code
<4> Set the label description
<5> Set the label width to 100%
<6> Add a CSS style class name

Other builders are available for the tags: `P`, `SPAN`, `H1`, `H2`, `H3`, `H4`, `H5`, `H6`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=label2,indent=0]
----
<1> Get a label builder using a `Paragraph` component
<2> Get a label builder using a `Span` component
<3> Get a label builder using a `H1` component
<4> Get a label builder using a `H2` component
<5> Get a label builder using a `H3` component
<6> Get a label builder using a `H4` component
<7> Get a label builder using a `H5` component
<8> Get a label builder using a `H6` component

===== Layouts

The Vaadin Flow base layouts can be created and configured using the following builders:

* *Vertical layout: * `Components.vl()`.
* *Horizontal layout: * `Components.hl()`.
* *Form layout: * `Components.formLayout()`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=layouts,indent=0]
----
<1> Get a `VerticalLayout` builder
<2> Enable spacing
<3> Enable margins
<4> Set the default component alignment
<5> Set the justify content mode
<6> Set width and height to 100%
<7> Add a CSS style class name 
<8> Add a Button component
<9> Add two label components
<10> Add a component and set its alignment 
<11> Get a `HorizontalLayout` builder 
<12> Add a component
<13> Add another component
<14> Set the flex grow ratio for the first component
<15> Get a `FormLayout` builder 
<16> Add a component
<17> Add a FormItem slot with a component and its label
<18> Set the responsive steps

===== Context menu

The `Components.contextMenu()` method can be used to configure a `ContextMenu` and bind it to a component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=ctxmenu,indent=0]
----
<1> Get a `ContextMenu` builder
<2> Add a menu item with a text and a click handler
<3> Add disabled a menu item with a localizable text
<4> Add a menu item using a component
<5> Add a menu open change listener
<6> Build the `ContextMenu` and bind it to the `myComponent` component

[[BaseConfigurators]]
==== Base components configurators

Besides the builders, the `Components` API provides a set of _configurator_ methods, which can be used to *configure existing UI components*. The available configurators acts on some base UI components: label, Button and layouts.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=configurators,indent=0]
----
<1> Configure the `Button`, setting a localizable text
<2> Configure the `VerticalLayout`, disabling spacing and adding a component

[[Dialogs]]
=== Dialogs

The `Components.dialog` sub-interface provides a set of method to build and configure a Vaadin Flow `Dialog`. Three types of dialogs are available, as described below.

==== Message Dialog

A *message dialog* is a `Dialog` which can be used to display a simple message to the user.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog1,indent=0]
----
<1> Build a message `Dialog` with given message text
<2> Build a message `Dialog` with given localizable message text and open it
<3> Shorter to build and show a message `Dialog` with a localizable message text

==== Confirm Dialog

A *confirm dialog* is a `Dialog` which can be used to display a simple message to the user and provides a `OK` button at the bottom right position.

The `OK` button can be configured using the dialog builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog2,indent=0]
----
<1> Get a confirm `Dialog` builder
<2> Set the localizable dialog message
<3> Configure the confirm dialog OK button
<4> Build and open the dialog
<5> Shorter to build and show a confirm `Dialog` with a localizable message text

==== Question Dialog

A *question dialog* is a `Dialog` which can be used to ask a question to the user and handle the user answer. A `QuestionDialogCallback` function must be provided to handle the user answer.

Two buttons are displayed at the bottom right position, which by default represents the `yes` or `no` answers. The buttons can be configured using the dialog builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog3,indent=0]
----
<1> Get a question `Dialog` builder, providing the user answer callback
<2> Set the localizable dialog message
<3> Configure the _confirm_ dialog button
<4> Configure the _deny_ dialog button
<5> Build and open the dialog
<6> Shorter to build and show a question `Dialog` with a localizable message text

==== Dialog configuration options

All the dialog builders provides a set of common `Dialog` configuration options, including:

* Dialog size configuration
* Dialog style configuration
* Dialog closing mode configuration and open change listener

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog4,indent=0]
----
<1> Set the dialog width
<2> Set the dialog height
<3> Add a CSS style class name
<4> Disable closing when `ESC` pressed
<5> Enable closing when user clicks outside the dialog
<6> Add a open change listener

==== Adding components to the Dialog

The dialog builders allow to add custom components to the `Dialog` content. The components can be added in two positions:

* In the main dialog content: will be placed after the dialog message label, if any.
* In the dialog bottom toolbar: will be placed before the standard dialog buttons, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog5,indent=0]
----
<1> Add a label component in the dialog content area
<2> Add a button component in the dialog toolbar

[[Listing]]
=== List data in grids

The link:{apidir}/com/holonplatform/vaadin/flow/components/ItemListing.html[ItemListing^] API represents a UI component which can be used to display data in a tabular way. 

Extends `HasComponent` (see <<HasComponent>>) and it is actually implemented using a Vaadin Flow `Grid` component.

A `ItemListing` is designed to display a set of data *items* of a specific type, each one rendered as a list _row_. An item is a collection of values, and each value is bound to a *property* definition of a specific type. 

Each `ItemListing` column is bound to an item _property_ by default, even if _virtual_ or calculated columns can be added to the listing.

Two `ItemListing` implementations are available: 

* `PropertyListing`: to use the Holon Platform _property model_ to represent the item properties and the `PropertyBox` type as item representation. See <<PropertyListing>>.

* `BeanListing`: to use a Java Bean class as item type and the bean property names as item properties. See <<BeanListing>>.

Each item listing implementation provides one or more suitable `builder` methods to obtain the _fluent_ builder to use to create and configure an item listing instance.

The same builders are also available from the `Components` API, through the `Components.listing` sub interface. See <<Components>>.

[[PropertyListing]]
==== PropertyListing

The link:{apidir}/com/holonplatform/vaadin/flow/components/PropertyListing.html[PropertyListing^] API is the default `ItemListing` implementation which uses the *Holon Platform link:holon-core.html#Property[Property model^]* to represent and manage the data items.

* A *property set* must be provided at `PropertyListing` costruction time. It represents the available item properties, each one bound by default to a listing _column_.

* The `PropertyBox` type is used to represent an _item instance_, using the listing property set. So each listing row is bound to a `PropertyBox` instance, which collects the property values to be displayed for each listing column.

For example, given the following property model definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=propertydef,indent=0]
----

A `PropertyListing` can be created in the following way:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing1,indent=0]
----
<1> Build a `PropertyListing` using the `SUBJECT` property set. The listing will provide two columns, one bound to the `ID` item property and the other bound to the `NAME` item property
<2> Build a `PropertyListing` using the `Components` API, directly providing the `ID` and `NAME` properties as listing property set
<3> Just like any `HasComponent` component type, the `getComponent()` method should be used to obtain the actual listing Component

[[BeanListing]]
==== BeanListing

The link:{apidir}/com/holonplatform/vaadin/flow/components/BeanListing.html[BeanListing^] API is the default `ItemListing` implementation to use a *Java Bean class* as item type.

* A *bean class* must be provided at `BeanListing` costruction time. The bean class _property names_ will be used as listing property set and so rendered as listing _columns_. For this reason the item listing property definition type is a `String`.

* Each listing _row_ is bound to a bean class instance, and the bean class _getters_ will be used to obtain the property value to be rendered for each listing column.

For example, given the following bean class definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=beandef,indent=0]
----

A `BeanListing` can be created in the following way:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing2,indent=0]
----
<1> Build a `BeanListing` using the `MyBean` class. The listing will provide two columns, one bound to the `id` bean property name and the other bound to the `name` bean property name
<2> Build a `BeanListing` using the `Components` API
<3> Just like any `HasComponent` component type, the `getComponent()` method should be used to obtain the actual listing Component

[[ItemListingDataSource]]
==== Item listing data source

To obtain the item set to display, an item listing needs a _data source_ to be configured. This can be achieved either using the `items(...)` or the `datasource(...)` builder methods, to provide a static set of items or a backend data connection respectively.

*1. Using a static set of items:*

The item listing item set can be provided at listing costruction time, using the `items(...)` or `addItem(...)` builder methods. The provided item instances must be of the same type of the listing item type.

The provided item will be displayed in the same order they are provided at construction time.

Example using a `PropertyListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing3,indent=0]
----
<1> Set the listing items
<2> Set the listing items using `addItem(...)`

Example using a `BeanListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing4,indent=0]
----
<1> Set the listing items
<2> Set the listing items using `addItem(...)`

*2. Using a `DataProvider`:*

A Vaadin `com.vaadin.flow.data.provider.DataProvider` can be used as items data source. This allows to provide a _dynamic_ set of items, for example using a backend service.

The `DataProvider` data type must be consistent with the listing item type.

Example using a `PropertyListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing5,indent=0]
----
<1> Obtain a `DataProvider` using the `PropertyBox` data type
<2> Set the data provider as listing data source

Example using a `BeanListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing6,indent=0]
----
<1> Obtain a `DataProvider` using the `MyBean` data type
<2> Set the data provider as listing data source

When a `DataProvider` is used as data source, the `refresh()` and `refreshItem(T item)` can be used to refresh the listing item set:

* The `refresh` method can be used to refresh the whole item set. In most cases, the data provider configured as data source will execute again a query to obtain the data from the backend.

* The `refreshItem` method can be used to refresh a single item, providing an updated instance to be included in the listing item set, replacing the previous one.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing7,indent=0]
----
<1> Create a listing and use a data provider as data source
<2> Refresh all the listing items
<3> Refresh a specific item

[[ItemListingDatastoreDataSource]]
==== Using a `Datastore` as item listing data source

The Holon Platform link:holon-core.html#Datastore[Datastore API^] can be used to implement a listing data source, and maybe it is the most straight and easy way to connect a _property model_ based listing to a backend data source.

This first way to use a `Datastore` as listing data source is to use the `DataProvider` adapter, available through the link:{apidir}/com/holonplatform/vaadin/flow/data/DatastoreDataProvider.html[DatastoreDataProvider^] API.

See the <<DatastoreIntegration>> section to learn how to create and configure a `Datastore` based `DataProvider`.

When a `Datastore` is used, a `DataTarget` definition is required to declare the data model _entity_ to use as items data source (for example a RDBMS table name, or a collection name in a document based database).

Supposing to use the following `DataTarget` definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=target,indent=0]
----

A `PropertyListing` data source can be declared as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing8,indent=0]
----
<1> Create a `PropertyListing` using the `SUBJECT` property set
<2> Use the `DatastoreDataProvider` API to create a data provider which uses the provided `Datastore` and `DataTarget` to perform backend data queries

But the most straight and easy way to use a `Datastore` as listing data source is to rely on the *listing builder methods* available for this purpose. Furthermore, the builder methods allow to avoid to specify the query projection *property set* again, using the listing property set by default.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing9,indent=0]
----
<1> Create a `PropertyListing` using the `SUBJECT` property set
<2> Directly use the `dataSource` builder method to create a data provider which uses the provided `Datastore` and `DataTarget` to perform backend data queries. In this case, there is no need to specify the `SUBJECT` property set, since the listing property set is used as query projection

The `dataSource` builder method turns the root listing builder in a Datastore-aware builder, making available a set of additional methods which can be used to configure the `Datastore` based data provider, for example to *add query filters and sorts*. The `Datastore` based data provider configuration methods corresponds to the ones provided by the `DatastoreDataProvider` API. See <<DatastoreQueryConfiguration>> for details.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing10,indent=0]
----
<1> Set the listing data source using a `Datastore` and providing the data target to use
<2> Configure the `Datastore` data provider adding a query filter
<3> Configure the `Datastore` data provider adding a query sort

[[ItemListingConfiguration]]
==== Item listing configuration

The item listing builders provides a set of methods to configure the item listing component, most of them coming from the Vaadin `Grid` component configuration options. 

This includes for example setting the page size, setting whether the listing column are resizable and can be reordered, setting the _frozen_ columns and so on.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing11,indent=0]
----
<1> Sets the page size (the number of items fetched at a time from the data source)
<2> Set whether the columns can by reordered by the user
<3> Set whether the columns can by resized by the user
<4> Set the number of _frozen_ columns, i.e. the fixed columns, not involved in horizontal scrolling
<5> Set whether the listing's height is defined by the number of its rows
<6> Set whether the vertical scrolling is enabled

[[ItemClickListener]]
==== Listen to listing row clicks

One ore more *item click listener* can be added to the listing to handle user clicks on the listing rows. The click event provides the clicked item instance and a reference to the listing on which the click occurred. 

Furthermore, a set of additional click information are provided, such as the click count, the modifier keys, the screen coordinates and so on.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing11b,indent=0]
----
<1> Add an item click listener
<2> Get the item instance on which the click occurred
<3> Get the item listing reference
<4> Get the consecutive clicks count
<5> Get the mouse button, if available
<6> Check whether the CTRL key was down when the click occurred

[[ItemListingColumns]]
==== Configure the item listing columns

The item listing columns are auto-generated by default using the provided listing *property set*. 

* `PropertyListing`: each property declared in the property set will be rendered as a column. You can refer to a column using the corresponding _property definition_.

* `BeanListing`: each available bean property will be rendered as a column. You can refer to a column using the corresponding bean _property name_.

===== Change the column order and visibility

A set of builder methods are available to change the listing column display order. The builder methods allow to:

* Explicitly provide the column to show and their order.
* Declare the column position relative to another column (before or after) 
* Display a column as first or last in the columns set
* Set a column as hidden

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing12,indent=0]
----
<1> Declare the visibile columns and the display order
<2> Set the `NAME` column to be displayed as first
<3> Set the `ID` column to be displayed as last
<4> Set the `NAME` column to be displayed before the `ID` column
<5> Set the `ID` column to be displayed after the `NAME` column
<6> Set the `ID` column as hidden
<7> Example using a `BeanListing`

===== Column configuration

The item listing builder provides a set of methods to configure a listing column, including:

* Se the column _header_, with *localizable messages* support. See <<I18n>>.
* Se the column _footer_, with *localizable messages* support. See <<I18n>>.
* Set the column width and alignment
* Set whether the column is resizable by the user
* Set whether the column is sortable and optionally provide the sort logic
* Set the column value provider and renderer
* Set whether the column is _frozen_, i.e. fixed and not involved in horizontal scrolling

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing13,indent=0]
----
<1> Set the `NAME` column header
<2> Set the `NAME` column header using a localizable message
<3> Set the `NAME` column width
<4> Set the `NAME` column flex grow ratio
<5> Set the `NAME` column alignment
<6> Set the `NAME` column footer
<7> Set whether the `NAME` column is resizable
<8> Set whether the `NAME` column is sortable
<9> Set that the `ID` property must be used to sort the `NAME` column
<10> Set the `NAME` column sort logic
<11> Set the `NAME` column value provider
<12> Set the `NAME` column renderer
<13> Set the `NAME` column as frozen

===== Adding columns

New _virtual_ columns can be added to an item listing, i.e. columns which are not directly bound to an item property.

A virtual column can be used for example to display a *calculated* result, using the item instance property values, or to display a *UI component*.

*1. Add a virtual column:*

A new column can be added to the listing using the `withColumn` builder method and providing a function to obtain the column value, given the current *row item instance* (a `PropertyBox` for a `PropertyListing` and a bean class instance for a `BeanListing`.

The added column can be *configured*, with the same configuration options described in the section above. Then, the column is added to the listing using the `add()` method.

Example using a `PropertyListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing14,indent=0]
----
<1> Add a new virtual column, which uses the row item to provide its value
<2> Configure the added column setting the header text
<3> Set to display the added column before the `NAME` column
<4> Add the column to the listing

Example using a `BeanListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing15,indent=0]
----
<1> Add a new virtual column, which uses the row item to provide its value
<2> Configure the added column setting the header text
<3> Set to display the added column as first
<4> Add the column to the listing

*2. Add a `Component` type column:*

A convenience `withComponentColumn` method is available to add a Vaadin `Component` type column, automatically configuring a suitable Component renderer for the column itself.

Just like a virtual column, the column can be configured and then the `add()` method should be used to add it to the listing.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing16,indent=0]
----
<1> Add a new `Component` type column, which provides a `Button` and uses the row item to set the button text
<2> Configure the added column setting the header text
<3> Set that the `NAME` property has to be used to sort the added column
<4> Add the column to the listing

[[ColumnRendering]]
==== Default column value rendering strategy

If an explicit column renderer is not configured for a column, the default column value rendering strategy uses the Holon Platform link:{coreapidir}/com/holonplatform/core/presentation/StringValuePresenter.html[StringValuePresenter^] API to render a column value.

This ensures a consistent behaviour across the application on how the values are displayed and the current `LocalizationContext` is used, if available, to apply the proper internationalization conventions to format, for example, a numeric value.

See the link:holon-core.html#StringValuePresenter[StringValuePresenter API^] documentation for details.

Furthermore, for a `PropertyListing` implementation, the link:{coreapidir}/com/holonplatform/core/property/PropertyValuePresenter.html[PropertyValuePresenter^] architecture is used to render the column value, allowing to extend and tune the presentation strategy at higher level, ensuring consistency across the application UI and backend.

See the link:holon-core.html#Property.presentation[Property value presentation^] documentation for details.

For example, suppose we want to add a `#` prefix to each value of the `ID` property. We can declare a `PropertyValuePresenter` and bind it to the `ID` property in the property presenters registry:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing17a,indent=0]
----
<1> Get the default `PropertyValuePresenterRegistry`
<2> Register a `PropertyValuePresenter`, bound to the `ID` property, which adds a `#` prefix to the property value

From now on, any `PropertyListing` instance will use the new presenter to render the `ID` property column value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing17b,indent=0]
----
<1> The `PropertyListing` instance will use the new presenter to render the `ID` property column value (so the `ID` column cells will show `#1`, `#2` and so on)
<2> Any other property presentation service will use the new presenter for the `ID` property value. In this example, the `ID` property is directly used to present the `1` value (declared as a Long) and the result will be the String `#1`.

[[ItemListingContextMenu]]
==== Add a context menu

The item listing supports a *context menu*, which can be added to the listing and will open by default when a _right click_ or a _long tap_ is performed by the user on a listing row.

The item listing context menu builder provides a set of methods to:

* Add context menu item using a *text*, with message localization support.
* Add context menu item using a *Component*.
* Set the menu item *click handler*, providing an event form which to obtain the *listing item instance* of the row on which to context menu was opened and a reference to the item listing itself.
* Configure the context menu items.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing18,indent=0]
----
<1> Create a context menu for the listing: a context menu builder is returned to configure the menu items
<2> Add a menu item with given text
<3> Configure the menu item adding the click handler
<4> The click event provides the listing item instance of the row on which to context menu was opened
<5> The parent item listing can be obtained from the click event
<6> Add the context menu item to the context menu
<7> Add another context menu item, directly providing a localizable text and the item click handler
<8> Add a `Component` type context menu item, directly providing a `Button` and the item click handler
<9> Add the configured context menu to the item listing

[[ItemListingRowDetails]]
==== Manage row details components

The item listing supports *row details* components, which can be opened and closed under each listing row. 

To enable the item row details, a function which provides the details content for each row has to be provided. For each row, the *listing row item* instance is provided as function argument.

The item details contents can be rendered in two ways:

* *As a text:* using the `itemDetailsText` builder method.
* *As a `Component`:* using the `itemDetailsComponent` builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing19,indent=0]
----
<1> Set the item details renderer using text
<2> Set the item details renderer using a `Component`

By default, the item details are shown/hidden for each listing row *when the user clicks on a row*. This behaviour can be disabled using the `itemDetailsVisibleOnClick` builder method.

In this case, the item details content should be opened or closed programmatically. For this purpose, the `setItemDetailsVisible` method of the item listing API can be use to show or hide the item details for a specific item.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing20,indent=0]
----
<1> Set the item details renderer using text
<2> Disable the item details display at user click
<3> Add an item click listener to handle the item details display, using the `setItemDetailsVisible` method

[[ItemListingHeaderFooter]]
==== Header and footer configuration

TBD

[[ItemListingSelection]]
==== Handling row selection

TBD

[[ItemListingEdit]]
==== Editing the listing items

TBD

[[View]]
=== View components and forms

TBD

[[Input]]
=== Input components and forms

TBD

[[PropertyRenderers]]
=== Property renderers for UI components

TBD

[[VaadinSessionScope]]
== Vaadin session scope

TBD

[[DeviceInfo]]
=== Device information

TBD




