[[VaadinFlowComponents]]
== Vaadin Flow UI components

The `holon-vaadin-flow` artifact is the main entry point to enable the Holon platform Vaadin Flow integration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow</artifactId>
<version>{revnumber}</version>
----

It provides integration between the Vaadin Flow core architecture and the Holon Platform one, providing also a set of UI components specifically designed to ensure a seamless integration with the Holon Platform Property model, Datastore API, authentication and internationalization APIs.

[[DatastoreIntegration]]
=== Datastore API integration

The Holon Platform link:holon-core.html#Datastore[Datastore API^] can be used to bind a UI component to backend data in a simple and powerful way, relying on the Holon Platform link:holon-core.html#Property[Property model^] to represent the underlying data model.

The link:{apidir}/com/holonplatform/vaadin/flow/data/DatastoreDataProvider.html[DatastoreDataProvider^] API is a standard Vaadin Flow `com.vaadin.flow.data.provider.DataProvider` which uses the `Datastore` API to fetch data from backend and makes available a set of configuration methods to control and setup the queries to perform.

Since it is a standard `DataProvider`, it can be seamlessy used in any Vaadin UI component which support data binding.

The `DatastoreDataProvider` provides a set of `create(..)` and `builder(..)` methods to build and configure a new `Datastore` based `DataProvider`. At least the following elements are required to create a `DatastoreDataProvider`:

* The reference to the `Datastore` instance to use.
* A `DataTarget` declaration, which represents the data model _entity_ to use as data source (for example, a RDBMS table name).

==== Item types

By default, the Holon Platform link:holon-core.html#Property[Property model^] is used to represent the backend data model attributes, and the link:holon-core.html#PropertyBox[PropertyBox^] type to represent a data source _item_, intended as a collection of properties and their values.

So, besides the `Datastore` reference and the `DataTarget` definition, the *property set* to use has to be provided to the `DatastoreDataProvider` builder methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider1,indent=0]
----
<1> Property set declaration
<2> Data target definition
<3> Datastore reference
<4> Create a new `DatastoreDataProvider` using the `SUBJECT` property set
<5> Create a new `DatastoreDataProvider` providing the `ID` and `NAME` properties as property set

Furthermore, the `DatastoreDataProvider` API provides methods to use a *bean class* as item type. The item property set is obtained form the bean class attributes, using the bean property names as property set property names.

TIP: See the link:holon-core.html#Beans[Java Beans and property model^] documentation section for information about the conventions and the configuration options which can be used when a Java Bean is used with the Holon Platform property model.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider2,indent=0]
----
<1> Data target definition
<2> Datastore reference
<3> Create a new `DatastoreDataProvider` using the `MyBean` class as item type

==== Filter types

By default, the `QueryFilter` type is used used as data provider filter type, since it is the default property model representation for the `Datastore` API query restrictions definition.

To use a different data provider filter type, a *filter converter function* can be configured for the `DatastoreDataProvider`, to provide the custom filter type to `QueryFilter` type conversion logic.

In the example below, a `String` type filter is used and the conversion function creates a `QueryFilter` which represents the condition "The `NAME` data model attribute value starts with the given filter value":

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider3,indent=0]
----

Similarly when a bean item type is used:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider4,indent=0]
----

==== Custom item and filter type

The `DatastoreDataProvider` API makes also available methods to customize both the item type and the data provider filter type, providing:

* The `PropertyBox` type to the custom item type conversion function.
* The custom filter type to the `QueryFilter` type conversion function.

For example, using a `MyItem` item class and a `String` filter type:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider5,indent=0]
----
<1> The `SUBJECT` property set is used as query projection
<2> Item conversion function: from the `PropertyBox` type object to the `MyItem` item type
<3> Filter conversion function: from a `String` type filter to a `QueryFilter` type

[[DatastoreQueryConfiguration]]
==== `Datastore` Query configuration

The queries performed by the `Datastore` to fetch the data from backend can be configured using the `DatastoreDataProvider` *builder API*.

===== Query filters and sorts

The query filters and sorts can be configured in two ways:

*1. At construction time, using the appropriate builder methods:* 

The `DatastoreDataProvider` builder API provide methods to:

* Add one or more `QueryFilter` to the query definition. These filters will always be included in the query execution.
* Add one or more `QuerySort` to the query definition. These sorts will always be included in the query execution.
* Set a default `QuerySort`, which will be used when no other sort is configured for the query.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider6,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a query filter
<3> Add a query sort
<4> Set the default query sort

*2. Dynamically, using a `QueryConfigurationProvider`:* 

One or more `QueryConfigurationProvider` references can be configured for the query using the `DatastoreDataProvider` builder API. 

At each query execution, the `getQueryFilter()` and `getQuerySort()` methods of each available `QueryConfigurationProvider` will be invoked to obtain the filters and sorts to add to the query, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider7,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a `QueryConfigurationProvider`
<3> At each query execution, this method will be invoked to obtain the query filters, if any
<4> At each query execution, this method will be invoked to obtain the query sorts, if any

===== `QuerySortOrder` conversion

When the standard Vaadin Flow `com.vaadin.flow.data.provider.QuerySortOrder` type is used for the data provider query configuration, the `DatastoreDataProvider` can be configured to control how a `QuerySortOrder` declaration is converted into a `QuerySort` definition.

For this purpose, the `DatastoreDataProvider` builder API allows to configure a `QuerySortOrder` conversion function.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider8,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Set the `QuerySortOrder` conversion function

===== Item identifier

By default, the item itself is used as _item identifier_ to discern each item from another within the query results. The item identification relies on the standard Java `equals` and `hashCode` object methods.

When a `PropertyBox` type item is used, the default item identification strategy relies on the property set *identifier properties* values, if declared.

TIP: See the link:holon-core.html#IdentifierProperties[Identifier properties^] documentation section for details.

If a custom item identifier should be used, an item identifier provider function can be configured using the `DatastoreDataProvider` builder API. This function must provide the item identifier for each item obtained form query execution.

.Example using a PropertyBox type item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider9,indent=0]
----
<1> Set an item identifier provider function which provides the `ID` property value as item identifier

.Example using a bean item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider10,indent=0]
----
<1> Set an item identifier provider function which provides the bean id value as item identifier using the `getId()` method

==== Setup a `Datastore` data provider using builders

The Holon Platform Vaadin Flow module _builder_ APIs provides covenient methods to setup a `Datastore` based data provider for UI components which support data binding.

Example for a _single select_, implemented using a Vaadin `ComboBox` component:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=builder,indent=0]
----

See <<Components>> to learn about the available component builders.

[[I18n]]
=== Internationalization

The Holon Platform Vaadin Flow module provides a complete integration with the Holon Platform link:holon-core.html#i18n[internationalization^] architecture, making UI components and messages localization simple and conistent with the full application stack.

Each localizable messages is represented by:

* A required *message code*, i.e. the `String` key to be used to obtain the message localization for a given `Locale`.
* An optional *default message*, to be used if a localized message is not available for a `Locale`.
* A set of optional *localization arguments*, which can be used to replace a specific _placeholder_ with the actual values.

The localizable message attributes described above can be declared and represented using the link:{coreapidir}/com/holonplatform/core/i18n/Localizable.html[Localizable^] interface, which provides convenient methods to create `Localizable` instances providing the message localization attributes.

The UI component builders which allow to setup localizable messages and texts, always support the `Localizable` API to provide the message localization attributes, providing also convenient methods to directly set the message localization attributes.

Example using a _button_ component builder:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=builder1,indent=0]
----
<1> Set the button text using a not localizable message
<2> Set the button text using a localizable message, providing the default message and the localization code
<3> Set the button text using a localizable message, also providing two message localization arguments 
<4> Set the button text using a `Localizable` reference

See <<Components>> to learn about the available component builders.

==== LocalizationContext and LocalizationProvider

The Holon Platform internationalization support relies on the link:holon-core.html#LocalizationContext[LocalizationContext^] API, which acts as message resolver, localized data formatter and holder for the current user `Locale`.

In order for the UI components localization to work, one of the following conditions must be met:

* A `LocalizationContext` is available as _context_ resource and a `Locale` is configured. See the Holon Platform link:holon-core.html#Context[Context^] architecture for information about the context resources management.

* Otherwise, a Vaadin Flow `I18NProvider` is available from the current Vaadin Service.

TIP: See <<VaadinSessionScope>> to learn about the _context scope_ for resources bound to the current Vaadin application session.

The link:{apidir}/com/holonplatform/vaadin/flow/i18n/LocalizationProvider.html[LocalizationProvider^] API is used by the UI components and builders to obtain the localization information and to localize the messages to display.

The `LocalizationProvider` API makes available a set of static methods to seamlessy integrate the messages localization in any part of the application, delegating the actual internationalization logic to the concrete localization provider, if available, which can be either a Holon Platform `LocalizationContext` or a Vaadin Flow `I18NProvider`.

The *actual localization service to use* is automatically detected with the following strategy:

* If a Vaadin Flow `I18NProvider` is available from current `VaadinService`, it is used for messages localization.
* Otherwise, a `LocalizationContext` is used if available as a _context_ resource.

This way, the `LocalizationProvider` API  `getLocalization` static methods can be used as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=localizationProvider1,indent=0]
----
<1> Get the localization for the given `Localizable` message using the given `Locale`
<2> Get the localization for the given `message.localization.code` message code using the given `Locale` and the default `Default message` message if the localization is not available

If the `Locale` is not explicitly provided, the `LocalizationProvider` API  `localize` static methods can be used and the *current Locale* is obtained with the following strategy:

* If a current `UI` is available and a `Locale` is configured for the `UI`, this one is used.
* If a `LocalizationContext` is available as a _context_ resource and it is localized, the `LocalizationContext` current `Locale` is used.
* If a Vaadin Flow `I18NProvider` is available from current `VaadinService`, the first provided `Locale` is used if available.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=localizationProvider2,indent=0]
----
<1> Get the current `Locale`, if available
<2> Get the localization for the given `Localizable` message using the current `Locale`
<3> Get the localization for the given `message.localization.code` message code using the current `Locale`: the default `Default message` message is returned if the message localization or the current `Locale` is not available

[[I18NProvider]]
==== Use a LocalizationContext as I18NProvider

The Holon Platform `LocalizationContext` can be used as a standard Vaadin Flow `I18NProvider` through the link:{apidir}/com/holonplatform/vaadin/flow/i18n/LocalizationContextI18NProvider.html[LocalizationContextI18NProvider^] API.

TIP: See the link:holon-core.html#LocalizationContext[LocalizationContext^] documentation for information about the `LocalizationContext` configuration and use.

The `LocalizationContextI18NProvider` provides static methods to build a `I18NProvider` instance which uses a `LocalizationContext` as message localizations provider.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=i18nprovider1,indent=0]
----
<1> Set the messages localization source
<2> Set the initial `Locale`
<3> Create a `I18NProvider` instance using the `LocalizationContext` as message localization provider

A `LocalizationContextI18NProvider` which uses the current `LocalizationContext` (if available as a _context_ resource) can be obtained with the `create()` method:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=i18nprovider2,indent=0]
----
<1> Create a `LocalizationContext`
<2> Put the `LocalizationContext` instance as a Vaadin Session attribute
<3> Create a `I18NProvider` instance which uses the current `LocalizationContext`

[[HasComponent]]
=== The `HasComponent` interface

Many of the additional UI components provided by the Holon Platform Vaadin Flow module extends the link:{apidir}/com/holonplatform/vaadin/flow/components/HasComponent.html[HasComponent^] interface to make available the actual Vaadin `com.vaadin.flow.component.Component` which can be used in the application UI. 

The `getComponent()` method should be used to obtain the actual `Component`, for example to add it to a layout.

This because all the Holon UI components are represented using an _interface_, while the Vaadin `Component` object is a _class_. For this reason, the UI component interface cannot directly extend a class and the actual Vaadin `Component` is thus provided through the `getComponent()` method.

Example for an `Input` type component:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=hascomponent,indent=0]
----
<1> Create a String type `Input`
<2> Use the `getComponent()` method to add the actual input component to a layout

All the Holon UI components interfaces are located in the `com.holonplatform.vaadin.flow.components` package.

Furthermore, the `HasComponent` API provides methods to check if the actual component supports a set of features and to obtain the appropriate interface which allow to manage a specific feature. 

Some of the component features which can be checked and accessed are:

* _Enabled mode_: using `hasEnabled()`.
* _Size_: using `hasSize()`.
* _Style_: using `hasStyle()`.
* _Label_: using `hasLabel()`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=hascomponent2,indent=0]
----
<1> Create a String type `Input`
<2> Check if the component supports the enabled mode and if so set it to `false`
<3> Check if the component supports size and if so set it to full
<4> Check if the component supports style and if so add a CSS style class name
<5> Check if the component supports a label and if so set it to `My label`

[[ValueHolder]]
=== The `ValueHolder` interface

The link:{apidir}/com/holonplatform/vaadin/flow/components/ValueHolder.html[ValueHolder^] API is the abstract representation for components which handle a *typed value*, allowing to get and set the value according to the value type with which they are declared.

A set of convenience methods are provided to check if the value holder is _empty_ (i.e. has no value) and to clear the value.

See <<View>> and <<Input>> to check two `ValueHolder` implementations.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=valueholder1,indent=0]
----
<1> Create a `String` type `Input`, which extends `ValueHolder`
<2> Set the value
<3> Get the value
<4> Get the value, if present
<5> Check whether the input is empty
<6> Clear the value

Furthermore, the `ValueHolder` type components allow to listen to value changes, using a `ValueChangeListener`. The value change event provides both the changed and the previous value, and the information about the value change context, including whether the value change was originated by a user action or programmatically.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=valueholder2,indent=0]
----
<1> Create a `String` type `Input`, which extends `ValueHolder`
<2> Add a `ValueChangeListener`
<3> Get the previous value
<4> Get the changed value
<5> Get whether the value change was originated by a user action or programmatically

[[Components]]
=== Component builders and providers

The link:{apidir}/com/holonplatform/vaadin/flow/components/Components.html[Components^] API is *the main entry point* to build and configure the UI components.

It provides a complete set of methods to obtain _fluent_ builders to create and configure both standard Vaadin Flow components and the additional UI components provided by the Holon Platform Vaadin Flow module.

The `Components` API structure:

|===
|Sub-interface |Provides

|*[NONE]*
|A set of _configure(*)_ methods to setup existing standard component instances and a set of methods to obtain the _fluent_ builders for base Vaadin components, such as `Button` and standard layout components. See <<BaseBuilders>>.

|*dialog*
|Message and question dialogs builders. See <<Dialogs>>.

|*view*
|Builders for view components and forms. See <<View>>.

|*input*
|Builders input components and forms. See <<Input>>.

|*listing*
|Builders for grid type components to list data. See <<Listing>>.
|===

==== Component builders structure

Each component builder API is composed by a set of specific builders, each related to a specific feature of the component. The feature builders are independent from the specific UI component to build, thus providing a common API which makes component configuration simple and intuitive.

For example, the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasTextConfigurator.html[HasTextConfigurator^] represents a builder part for UI components which supports a _text_, and it is included in any builder for UI components with text support.

Similarly, the the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasSizeConfigurator.html[HasSizeConfigurator^] API is included in component builders which supports the component _size_ configuration.

This ensures a consistent and common API to build and configure any UI component.

In the example below, the `HasTextConfigurator` and the `HasSizeConfigurator` are used in the same way to configure a _label_ and a _button_ component text and size:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=builders1,indent=0]
----
<1> Get a _label_ component builder
<2> Set the label text (using the `HasTextConfigurator` API)
<3> Set the label width (using the `HasSizeConfigurator` API)
<4> Get a _button_ component builder
<5> Set the button text (using the `HasTextConfigurator` API)
<6> Set the button width (using the `HasSizeConfigurator` API)

[[BaseBuilders]]
==== Base components builders

===== Button

The `Components.button()` method provides a standard Vaadin `Button` component builder, with localizable text support.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=button,indent=0]
----
<1> Get the `Button` builder
<2> Set the button text
<3> Set the button localizable text, providing a default text and a message localization code
<4> Set the button description
<5> Set the button width to 100%
<6> Add a CSS style class name
<7> Add a theme variant
<8> Set the button icon
<9> Automatically disables button when clicked
<10> Add a click event listener
<11> Shorter to directly create a `Button` providing the text and the click handler

The `Components.nativeButton()` builder can be used to build a `NativeButton` component.

===== Label

A _label_ component can be used to display a text, which can be *localizable*, and can be implemented using a set of tags. The default tag used by the `Components.label()` method is `DIV`.

TIP: See <<I18n>> for information about the UI components text localization.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=label1,indent=0]
----
<1> Get a label builder using a `Div` component
<2> Set the label text
<3> Set the label localizable text, providing a default text and a message localization code
<4> Set the label description
<5> Set the label width to 100%
<6> Add a CSS style class name

Other builders are available for the tags: `P`, `SPAN`, `H1`, `H2`, `H3`, `H4`, `H5`, `H6`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=label2,indent=0]
----
<1> Get a label builder using a `Paragraph` component
<2> Get a label builder using a `Span` component
<3> Get a label builder using a `H1` component
<4> Get a label builder using a `H2` component
<5> Get a label builder using a `H3` component
<6> Get a label builder using a `H4` component
<7> Get a label builder using a `H5` component
<8> Get a label builder using a `H6` component

===== Layouts

The Vaadin Flow base layouts can be created and configured using the following builders:

* *Vertical layout: * `Components.vl()`.
* *Horizontal layout: * `Components.hl()`.
* *Form layout: * `Components.formLayout()`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=layouts,indent=0]
----
<1> Get a `VerticalLayout` builder
<2> Enable spacing
<3> Enable margins
<4> Set the default component alignment
<5> Set the justify content mode
<6> Set width and height to 100%
<7> Add a CSS style class name 
<8> Add a Button component
<9> Add two label components
<10> Add a component and set its alignment 
<11> Get a `HorizontalLayout` builder 
<12> Add a component
<13> Add another component
<14> Set the flex grow ratio for the first component
<15> Get a `FormLayout` builder 
<16> Add a component
<17> Add a FormItem slot with a component and its label
<18> Set the responsive steps

===== Context menu

The `Components.contextMenu()` method can be used to configure a `ContextMenu` and bind it to a component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=ctxmenu,indent=0]
----
<1> Get a `ContextMenu` builder
<2> Add a menu item with a text and a click handler
<3> Add disabled a menu item with a localizable text
<4> Add a menu item using a component
<5> Add a menu open change listener
<6> Build the `ContextMenu` and bind it to the `myComponent` component

[[BaseConfigurators]]
==== Base components configurators

Besides the builders, the `Components` API provides a set of _configurator_ methods, which can be used to *configure existing UI components*. The available configurators acts on some base UI components: label, Button and layouts.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=configurators,indent=0]
----
<1> Configure the `Button`, setting a localizable text
<2> Configure the `VerticalLayout`, disabling spacing and adding a component

[[Dialogs]]
=== Dialogs

The `Components.dialog` sub-interface provides a set of method to build and configure a Vaadin Flow `Dialog`. Three types of dialogs are available, as described below.

==== Message Dialog

A *message dialog* is a `Dialog` which can be used to display a simple message to the user.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog1,indent=0]
----
<1> Build a message `Dialog` with given message text
<2> Build a message `Dialog` with given localizable message text and open it
<3> Shorter to build and show a message `Dialog` with a localizable message text

==== Confirm Dialog

A *confirm dialog* is a `Dialog` which can be used to display a simple message to the user and provides a `OK` button at the bottom right position.

The `OK` button can be configured using the dialog builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog2,indent=0]
----
<1> Get a confirm `Dialog` builder
<2> Set the localizable dialog message
<3> Configure the confirm dialog OK button
<4> Build and open the dialog
<5> Shorter to build and show a confirm `Dialog` with a localizable message text

==== Question Dialog

A *question dialog* is a `Dialog` which can be used to ask a question to the user and handle the user answer. A `QuestionDialogCallback` function must be provided to handle the user answer.

Two buttons are displayed at the bottom right position, which by default represents the `yes` or `no` answers. The buttons can be configured using the dialog builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog3,indent=0]
----
<1> Get a question `Dialog` builder, providing the user answer callback
<2> Set the localizable dialog message
<3> Configure the _confirm_ dialog button
<4> Configure the _deny_ dialog button
<5> Build and open the dialog
<6> Shorter to build and show a question `Dialog` with a localizable message text

==== Dialog configuration options

All the dialog builders provides a set of common `Dialog` configuration options, including:

* Dialog size configuration
* Dialog style configuration
* Dialog closing mode configuration and open change listener

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog4,indent=0]
----
<1> Set the dialog width
<2> Set the dialog height
<3> Add a CSS style class name
<4> Disable closing when `ESC` pressed
<5> Enable closing when user clicks outside the dialog
<6> Add a open change listener

==== Adding components to the Dialog

The dialog builders allow to add custom components to the `Dialog` content. The components can be added in two positions:

* In the main dialog content: will be placed after the dialog message label, if any.
* In the dialog bottom toolbar: will be placed before the standard dialog buttons, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog5,indent=0]
----
<1> Add a label component in the dialog content area
<2> Add a button component in the dialog toolbar

[[Listing]]
=== List data in grids

The link:{apidir}/com/holonplatform/vaadin/flow/components/ItemListing.html[ItemListing^] API represents a UI component which can be used to display data in a tabular way. 

Extends `HasComponent` (see <<HasComponent>>) and it is actually implemented using a Vaadin Flow `Grid` component.

A `ItemListing` is designed to display a set of data *items* of a specific type, each one rendered as a list _row_. An item is a collection of values, and each value is bound to a *property* definition of a specific type. 

Each `ItemListing` column is bound to an item _property_ by default, even if _virtual_ or calculated columns can be added to the listing.

Two `ItemListing` implementations are available: 

* `PropertyListing`: to use the Holon Platform _property model_ to represent the item properties and the `PropertyBox` type as item representation. See <<PropertyListing>>.

* `BeanListing`: to use a Java Bean class as item type and the bean property names as item properties. See <<BeanListing>>.

Each item listing implementation provides one or more suitable `builder` methods to obtain the _fluent_ builder to use to create and configure an item listing instance.

The same builders are also available from the `Components` API, through the `Components.listing` sub interface. See <<Components>>.

[[PropertyListing]]
==== PropertyListing

The link:{apidir}/com/holonplatform/vaadin/flow/components/PropertyListing.html[PropertyListing^] API is the default `ItemListing` implementation which uses the *Holon Platform link:holon-core.html#Property[Property model^]* to represent and manage the data items.

* A *property set* must be provided at `PropertyListing` costruction time. It represents the available item properties, each one bound by default to a listing _column_.

* The `PropertyBox` type is used to represent an _item instance_, using the listing property set. So each listing row is bound to a `PropertyBox` instance, which collects the property values to be displayed for each listing column.

For example, given the following property model definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=propertydef,indent=0]
----

A `PropertyListing` can be created in the following way:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing1,indent=0]
----
<1> Build a `PropertyListing` using the `SUBJECT` property set. The listing will provide two columns, one bound to the `ID` item property and the other bound to the `NAME` item property
<2> Build a `PropertyListing` using the `Components` API, directly providing the `ID` and `NAME` properties as listing property set
<3> Just like any `HasComponent` component type, the `getComponent()` method should be used to obtain the actual listing Component

[[BeanListing]]
==== BeanListing

The link:{apidir}/com/holonplatform/vaadin/flow/components/BeanListing.html[BeanListing^] API is the default `ItemListing` implementation to use a *Java Bean class* as item type.

* A *bean class* must be provided at `BeanListing` costruction time. The bean class _property names_ will be used as listing property set and so rendered as listing _columns_. For this reason the item listing property definition type is a `String`.

* Each listing _row_ is bound to a bean class instance, and the bean class _getters_ will be used to obtain the property value to be rendered for each listing column.

For example, given the following bean class definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=beandef,indent=0]
----

A `BeanListing` can be created in the following way:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing2,indent=0]
----
<1> Build a `BeanListing` using the `MyBean` class. The listing will provide two columns, one bound to the `id` bean property name and the other bound to the `name` bean property name
<2> Build a `BeanListing` using the `Components` API
<3> Just like any `HasComponent` component type, the `getComponent()` method should be used to obtain the actual listing Component

[[ItemListingDataSource]]
==== Item listing data source

To obtain the item set to display, an item listing needs a _data source_ to be configured. This can be achieved either using the `items(...)` or the `datasource(...)` builder methods, to provide a static set of items or a backend data connection respectively.

*1. Using a static set of items:*

The item listing item set can be provided at listing costruction time, using the `items(...)` or `addItem(...)` builder methods. The provided item instances must be of the same type of the listing item type.

The provided item will be displayed in the same order they are provided at construction time.

Example using a `PropertyListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing3,indent=0]
----
<1> Set the listing items
<2> Set the listing items using `addItem(...)`

Example using a `BeanListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing4,indent=0]
----
<1> Set the listing items
<2> Set the listing items using `addItem(...)`

*2. Using a `DataProvider`:*

A Vaadin `com.vaadin.flow.data.provider.DataProvider` can be used as items data source. This allows to provide a _dynamic_ set of items, for example using a backend service.

The `DataProvider` data type must be consistent with the listing item type.

Example using a `PropertyListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing5,indent=0]
----
<1> Obtain a `DataProvider` using the `PropertyBox` data type
<2> Set the data provider as listing data source

Example using a `BeanListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing6,indent=0]
----
<1> Obtain a `DataProvider` using the `MyBean` data type
<2> Set the data provider as listing data source

When a `DataProvider` is used as data source, the `refresh()` and `refreshItem(T item)` can be used to refresh the listing item set:

* The `refresh` method can be used to refresh the whole item set. In most cases, the data provider configured as data source will execute again a query to obtain the data from the backend.

* The `refreshItem` method can be used to refresh a single item, providing an updated instance to be included in the listing item set, replacing the previous one.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing7,indent=0]
----
<1> Create a listing and use a data provider as data source
<2> Refresh all the listing items
<3> Refresh a specific item

[[ItemListingDatastoreDataSource]]
==== Using a `Datastore` as item listing data source

The Holon Platform link:holon-core.html#Datastore[Datastore API^] can be used to implement a listing data source, and maybe it is the most straight and easy way to connect a _property model_ based listing to a backend data source.

This first way to use a `Datastore` as listing data source is to use the `DataProvider` adapter, available through the link:{apidir}/com/holonplatform/vaadin/flow/data/DatastoreDataProvider.html[DatastoreDataProvider^] API.

See the <<DatastoreIntegration>> section to learn how to create and configure a `Datastore` based `DataProvider`.

When a `Datastore` is used, a `DataTarget` definition is required to declare the data model _entity_ to use as items data source (for example a RDBMS table name, or a collection name in a document based database).

Supposing to use the following `DataTarget` definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=target,indent=0]
----

A `PropertyListing` data source can be declared as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing8,indent=0]
----
<1> Create a `PropertyListing` using the `SUBJECT` property set
<2> Use the `DatastoreDataProvider` API to create a data provider which uses the provided `Datastore` and `DataTarget` to perform backend data queries

But the most straight and easy way to use a `Datastore` as listing data source is to rely on the *listing builder methods* available for this purpose. Furthermore, the builder methods allow to avoid to specify the query projection *property set* again, using the listing property set by default.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing9,indent=0]
----
<1> Create a `PropertyListing` using the `SUBJECT` property set
<2> Directly use the `dataSource` builder method to create a data provider which uses the provided `Datastore` and `DataTarget` to perform backend data queries. In this case, there is no need to specify the `SUBJECT` property set, since the listing property set is used as query projection

The `dataSource` builder method turns the root listing builder in a Datastore-aware builder, making available a set of additional methods which can be used to configure the `Datastore` based data provider, for example to *add query filters and sorts*. The `Datastore` based data provider configuration methods corresponds to the ones provided by the `DatastoreDataProvider` API. See <<DatastoreQueryConfiguration>> for details.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing10,indent=0]
----
<1> Set the listing data source using a `Datastore` and providing the data target to use
<2> Configure the `Datastore` data provider adding a query filter
<3> Configure the `Datastore` data provider adding a query sort

[[ItemListingFrozenState]]
==== Item listing _frozen_ data source modality

The item listing data source can be set in a _frozen_ state using the item listing API:

* When the item listing is in _frozen_ state, it *never shows any item* and *no fetch is performed* from the data provider.
* When the item listing `refresh()` method is invoked, the _frozen_ state is automatically disabled, allowing the listing to fetch and display the items.

The _frozen_ state can be useful when you don't want to fetch the items just after the listing is displayed in UI, maybe because it involves an onerous backend query. The backend query is only performed when the `refresh()` method is called, typically by a user explicit action.

The item listing _frozen_ state can be configured either from the buider API or from the `ItemListing` API:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing31,indent=0]
----
<1> Use the builder API to set the listing in _frozen_ state
<2> Use the listing API to set the listing in _frozen_ state
<3> Check whether the listing is in _frozen_ state
<4> Calling `refresh()` will disable the _frozen_ state, allowing the listing to fetch and display the items

[[ItemListingAdditionalItems]]
==== Item listing data source additional items

The `ItemListing` API supports _additional_ data source items. Additional items can be added using the `ItemListing` API and they will appear as conventional listing items, even they are not part of the items returned by the concrete data source.

Additional items can be used, for example, to allow the user to *add* an item to the listing, edit its data and then saving the item in the concrete datastore. At this point, the additional item can be removed, since the saved item will now be returned by the data source query.

The `ItemListing` API provides method to manage additional items: add an additional item, remove an additional item, remove all additional items and obtain the current additional items.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing32,indent=0]
----
<1> Add an additional item
<2> Get the current additional items
<3> Remove the additional item
<4> Remove all the additional items

[[ItemListingConfiguration]]
==== Item listing configuration

The item listing builders provides a set of methods to configure the item listing component, most of them coming from the Vaadin `Grid` component configuration options. 

This includes for example setting the page size, setting whether the listing column are resizable and can be reordered, setting the _frozen_ columns and so on.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing11,indent=0]
----
<1> Sets the page size (the number of items fetched at a time from the data source)
<2> Set whether the columns can by reordered by the user
<3> Set whether the columns can by resized by the user
<4> Set the number of _frozen_ columns, i.e. the fixed columns, not involved in horizontal scrolling
<5> Set whether the listing's height is defined by the number of its rows
<6> Set whether the vertical scrolling is enabled
<7> Set whether multiple column sorting is enabled on the client-side

[[ItemClickListener]]
==== Listen to listing row clicks

One ore more *item click listener* can be added to the listing to handle user clicks on the listing rows. The click event provides the clicked item instance and a reference to the listing on which the click occurred. 

Furthermore, a set of additional click information are provided, such as the click count, the modifier keys, the screen coordinates and so on.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing11b,indent=0]
----
<1> Add an item click listener
<2> Get the item instance on which the click occurred
<3> Get the item listing reference
<4> Get the consecutive clicks count
<5> Get the mouse button, if available
<6> Check whether the CTRL key was down when the click occurred

[[ItemListingColumns]]
==== Configure the item listing columns

The item listing columns are auto-generated by default using the provided listing *property set*. 

* `PropertyListing`: each property declared in the property set will be rendered as a column. You can refer to a column using the corresponding _property definition_.

* `BeanListing`: each available bean property will be rendered as a column. You can refer to a column using the corresponding bean _property name_.

===== Change the column order and visibility

A set of builder methods are available to change the listing column display order. The builder methods allow to:

* Explicitly provide the column to show and their order.
* Declare the column position relative to another column (before or after) 
* Display a column as first or last in the columns set
* Set a column as hidden

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing12,indent=0]
----
<1> Declare the visibile columns and the display order
<2> Set the `NAME` column to be displayed as first
<3> Set the `ID` column to be displayed as last
<4> Set the `NAME` column to be displayed before the `ID` column
<5> Set the `ID` column to be displayed after the `NAME` column
<6> Set the `ID` column as hidden
<7> Example using a `BeanListing`

===== Column configuration

The item listing builder provides a set of methods to configure a listing column, including:

* Se the column _header_, with *localizable messages* support. See <<I18n>>.
* Se the column _footer_, with *localizable messages* support. See <<I18n>>.
* Set the column width and alignment
* Set whether the column is resizable by the user
* Set whether the column is sortable and optionally provide the sort logic
* Set the column value provider and renderer
* Set whether the column is _frozen_, i.e. fixed and not involved in horizontal scrolling

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing13,indent=0]
----
<1> Set the `NAME` column header
<2> Set the `NAME` column header using a localizable message
<3> Set the `NAME` column header using a `Component`
<4> Set the `NAME` column width
<5> Set the `NAME` column flex grow ratio
<6> Set the `NAME` column alignment
<7> Set the `NAME` column footer
<8> Set whether the `NAME` column is resizable
<9> Set whether the `NAME` column is sortable
<10> Set that the `ID` property must be used to sort the `NAME` column
<11> Set the `NAME` column sort logic
<12> Set the `NAME` column value provider
<13> Set the `NAME` column renderer
<14> Set the `NAME` column as frozen

===== Adding columns

New _virtual_ columns can be added to an item listing, i.e. columns which are not directly bound to an item property.

A virtual column can be used for example to display a *calculated* result, using the item instance property values, or to display a *UI component*.

*1. Add a virtual column:*

A new column can be added to the listing using the `withColumn` builder method and providing a function to obtain the column value, given the current *row item instance* (a `PropertyBox` for a `PropertyListing` and a bean class instance for a `BeanListing`.

The added column can be *configured*, with the same configuration options described in the section above. Then, the column is added to the listing using the `add()` method.

Example using a `PropertyListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing14,indent=0]
----
<1> Add a new virtual column, which uses the row item to provide its value
<2> Configure the added column setting the header text
<3> Set to display the added column before the `NAME` column
<4> Add the column to the listing

Example using a `BeanListing`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing15,indent=0]
----
<1> Add a new virtual column, which uses the row item to provide its value
<2> Configure the added column setting the header text
<3> Set to display the added column as first
<4> Add the column to the listing

*2. Add a `Component` type column:*

A convenience `withComponentColumn` method is available to add a Vaadin `Component` type column, automatically configuring a suitable Component renderer for the column itself.

Just like a virtual column, the column can be configured and then the `add()` method should be used to add it to the listing.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing16,indent=0]
----
<1> Add a new `Component` type column, which provides a `Button` and uses the row item to set the button text
<2> Configure the added column setting the header text
<3> Set that the `NAME` property has to be used to sort the added column
<4> Add the column to the listing

[[ColumnRendering]]
==== Default column value rendering strategy

If an explicit column renderer is not configured for a column, the default column value rendering strategy uses the Holon Platform link:{coreapidir}/com/holonplatform/core/presentation/StringValuePresenter.html[StringValuePresenter^] API to render a column value.

This ensures a consistent behaviour across the application on how the values are displayed and the current `LocalizationContext` is used, if available, to apply the proper internationalization conventions to format, for example, a numeric value.

See the link:holon-core.html#StringValuePresenter[StringValuePresenter API^] documentation for details.

Furthermore, for a `PropertyListing` implementation, the link:{coreapidir}/com/holonplatform/core/property/PropertyValuePresenter.html[PropertyValuePresenter^] architecture is used to render the column value, allowing to extend and tune the presentation strategy at higher level, ensuring consistency across the application UI and backend.

See the link:holon-core.html#Property.presentation[Property value presentation^] documentation for details.

For example, suppose we want to add a `#` prefix to each value of the `ID` property. We can declare a `PropertyValuePresenter` and bind it to the `ID` property in the property presenters registry:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing17a,indent=0]
----
<1> Get the default `PropertyValuePresenterRegistry`
<2> Register a `PropertyValuePresenter`, bound to the `ID` property, which adds a `#` prefix to the property value

From now on, any `PropertyListing` instance will use the new presenter to render the `ID` property column value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing17b,indent=0]
----
<1> The `PropertyListing` instance will use the new presenter to render the `ID` property column value (so the `ID` column cells will show `#1`, `#2` and so on)
<2> Any other property presentation service will use the new presenter for the `ID` property value. In this example, the `ID` property is directly used to present the `1` value (declared as a Long) and the result will be the String `#1`.

[[ColumnComponentRendering]]
==== Render columns using Components

The `PropertyListing` builder makes available helper methods to render a column using a `Component`, providing the function to use to obtain the `Component` instance for each cell, given the current row `PropertyBox` item.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing17c,indent=0]
----
<1> Render the column identified by the `NAME` property as a `Component`. In this example, a `Button` is returned, with button text setted as the current item `NAME` property value

[[ColumnViewComponentRendering]]
==== Render columns using a `ViewComponent`

A `PropertyListing` column can be rendered using a `ViewComponent`, leveraging the `ViewComponent` rendering architecture and thus providing a consistent data rendering strategy across all the application UI components.

See <<View>> for information about `ViewComponent` purpose and configuration.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing17d,indent=0]
----
<1> The column identified by the `NAME` property will be rendered using a `ViewComponent`

[[ItemListingContextMenu]]
==== Add a context menu

The item listing supports a *context menu*, which can be added to the listing and will open by default when a _right click_ or a _long tap_ is performed by the user on a listing row.

The item listing context menu builder provides a set of methods to:

* Add context menu item using a *text*, with message localization support.
* Add context menu item using a *Component*.
* Set the menu item *click handler*, providing an event form which to obtain the *listing item instance* of the row on which to context menu was opened and a reference to the item listing itself.
* Configure the context menu items.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing18,indent=0]
----
<1> Create a context menu for the listing: a context menu builder is returned to configure the menu items
<2> Add a menu item with given text
<3> Configure the menu item adding the click handler
<4> The click event provides the listing item instance of the row on which to context menu was opened
<5> The parent item listing can be obtained from the click event
<6> Add the context menu item to the context menu
<7> Add another context menu item, directly providing a localizable text and the item click handler
<8> Add a `Component` type context menu item, directly providing a `Button` and the item click handler
<9> Add the configured context menu to the item listing

[[ItemListingRowDetails]]
==== Manage row details components

The item listing supports *row details* components, which can be opened and closed under each listing row. 

To enable the item row details, a function which provides the details content for each row has to be provided. For each row, the *listing row item* instance is provided as function argument.

The item details contents can be rendered in two ways:

* *As a text:* using the `itemDetailsText` builder method.
* *As a `Component`:* using the `itemDetailsComponent` builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing19,indent=0]
----
<1> Set the item details renderer using text
<2> Set the item details renderer using a `Component`

By default, the item details are shown/hidden for each listing row *when the user clicks on a row*. This behaviour can be disabled using the `itemDetailsVisibleOnClick` builder method.

In this case, the item details content should be opened or closed programmatically. For this purpose, the `setItemDetailsVisible` method of the item listing API can be use to show or hide the item details for a specific item.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing20,indent=0]
----
<1> Set the item details renderer using text
<2> Disable the item details display at user click
<3> Add an item click listener to handle the item details display, using the `setItemDetailsVisible` method

[[ItemListingHeaderFooter]]
==== Header and footer configuration

The item listing header and footer sections can be completely customized, setting the cells contents and joining two or more cells together.

The header and footer sections handlers can be obtainer either using:

* The builder API, using the `header` and `footer` methods.
* The item listing API, using the `getHeader()` and `getFooter()` methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing21,indent=0]
----
<1> Use the builder to customize the header section
<2> Use the builder to customize the footer section
<3> Get the header section
<4> Get the footer section

[[ItemListingSelection]]
==== Handling row selection

The item listing supports both *single* and *multiple* row selection modes. When the listing is in multiple selection mode, a _checkbox_ is shown before each listing row to allow user selection. Additionaly, a _select all_ checkbox is available in the listing header first cell.

The item listing selection mode can be enabled either using:

* The builder API, using the `selectionMode` method (`NONE`, `SINGLE` or `MULTI`). The `singleSelect()` and `multiSelect()` convenience methods are provided as shorters for the single and multiple selection mode.

* The item listing API, using the `setSelectionMode` method (`NONE`, `SINGLE` or `MULTI`).

A `SelectionListener` can be added to the item listing in order to listen to item selection events and obtain the currently selected items.

Furthermore, the item listing API provides a set of methods to select or deselect one or more items programmatically.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing22,indent=0]
----
<1> Set the listing selection mode
<2> Set the listing selection mode as single
<3> Set the listing selection mode as multiple
<4> Add a selection listener
<5> Get the selected items, if any
<6> Get the first selected item, if any
<7> Use the listing API to change the selection mode
<8> Add a selection listener
<9> Programmatically select an item
<10> Programmatically deselect an item
<11> Deselect all items

[[ItemListingEdit]]
==== Editing the listing items

The item listing supports an *edit mode*, which can be enabled using the `editable()` builder method.

When a listing is editable, a row can be setted in edit mode using the `editItem(T item)` method of the item listing API. When `editItem` is called, each cell content is replaced by an *input component* to allow to change the item property value which corresponds to each column.

The updated row item values can be saved using the `saveEditingItem()` method of the item listing API, or discarded using the `cancelEditing()` method. Then the row editor is closed, restoring the default cell contents.

A set of listeners can be added to the listing to control the editing process:

* `EditorSaveListener`: for editor save events, which corresponds to the `saveEditingItem()` method call. Can be used for example to update the data in the backend.
* `EditorCancelListener`: for editor cancel events, which corresponds to the `cancelEditing()` method call.
* `EditorOpenListener` / `EditorCloseListener`: for editor open and close events.

The component to use as input to edit each item property value can be customized using the `editorComponent(...)` builder method.

The row editor provides a *buffered* mode: when enabled, the edited values are setted into the item instance only when the `saveEditingItem()` method is called, for example using a provided _save_ button. The `editorBuffered` builder method can be used to enable or disable the buffered mode.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing23,indent=0]
----
<1> Enable the editable mode
<2> Set the editor in buffered mode
<3> Add a new column to provide the `Edit` button for each row, using the `editItem` method to edit the current row item
<4> Set the editor component for the added column: it will be displayed when the row is in edit mode, providing the `Save` and `Cancel` buttons, which invoke the `saveEditingItem()` and the `cancelEditing()` methods respectively
<5> Configure the added column to be displayed as first column
<6> Add the column to the listing
<7> Add an editor save listener to update the item data in backend
<8> The save event provides the edited item instance

===== Default editor components and customization 

By default, when a row is turned into edit mode, the Holon PropertyRenderer architecture is used to obtain an `Input` type component for each item property to edit (See <<Input>> for information on the `Input` component API).

TIP: See the link:holon-core.html#PropertyRenderer[Property renderering^] documentation for details about the property renderers architecture.

The editor component for a listing item property (and so for a listing column), can be configured using the following builder methods:

* `editor`: to set a `Input` as editor component. See <<Input>>.
* `editorField`: to use a standard Vaadin `HasValue` component as editor component.
* `editorComponent`: to use generic `Component` as editor component. 

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing24,indent=0]
----
<1> Set the editor `Input` to use for the `NAME` property/column
<2> Set the editor `Input` to use for the `NAME` property/column
<3> Set the editor `Input` to use for the `ID` property/column, providing a `Long` to `String` and back converter
<4> Set the editor `HasValue` component to use for the `NAME` property/column
<5> Set the editor `HasValue` component to use for the `ID` property/column, providing a `Long` to `String` and back converter
<6> Set a generic component as `ID` property/column editor component

Since the `PropertyRenderer` based architecture is used to obtain the editor components by default using the `Input` rendering type, the editor component can customized also by adding a new `PropertyRenderer` for a property definition. This ensures consistency across the application, and can be used to automatically configure the editor components for any item listing instance.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing25,indent=0]
----
<1> Add a new `PropertyRenderer` to the default registry to render the `NAME` property using the provided _stringArea_ type `Input` component.
<2> Any item listing which includes the `NAME` property will use the registered renderer to obtain the `Input` component to use as the `NAME` property/column editor

===== Data validation

To validate the user input when a listing row is in edit mode, the standard Holon link:holon-core.html#Validator[Validator^] API can be used.

When the editor _save_ action is performed (using the `saveEditingItem()` item listing API method), all the registered validators are invoked and the save operation is interrupted if one ore more validators fails, notifying the validation errors to the user.

*1. Property level validators:*

One or more validators can be bound to an item property to perform the property value validation. The property value validation is performed when the user leaves an editor component and when the editor _save_ action in invoked.

Any validator bound to a property at property definition time are *automatically inherited* as item property value validators.

New validators can be added to an item property using the `withValidator` item listing builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing26,indent=0]
----
<1> The _notBlank_ validator is added to the `NAME` property at definition time, so it will be inherited from the item listing editor validation
<2> A _max_ validator is added to the `NAME` property to ensure the String value is maximum 10 characters long

*2. Row level validators:*

One or more row level validators can be added to an item listing using the `withValidator` builder method. The row level validators are invoked when the editor _save_ action is performed, and the current item state s provided to validators to perform the required checks.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing27,indent=0]
----
<1> Add a row level validator

===== Validation status handler

By default, the validation errors originated by the registered validators are notified to the user in the following way:

* For property level validators, if the editor component supports error messages notification (using the Vaadin `HasValidation` interface), the validation errors are setted as component errors.
* For row level validators, a Dialog is used to notify the validation errors.

The validation status errors notification can be customized using the link:{apidir}/com/holonplatform/vaadin/flow/components/ValidationStatusHandler.html[ValidationStatusHandler^] interface, both at property and row level.

The `ValidationStatusHandler` validation event provides the validation status (valid, invalid or unresolved) and the current validation errors, if any. 

To customize both the *property level* and the *row level* validation status notification, the `validationStatusHandler` builder method can be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing28,indent=0]
----
<1> Set a custom row level validation status handler
<2> Set a custom property level validation status handler for the `NAME` property

Furthermore, the link:{apidir}/com/holonplatform/vaadin/flow/components/GroupValidationStatusHandler.html[GroupValidationStatusHandler^] interface can be used to override all the validation status notification, customizing both the property level and the row level validation status notification using a single handler.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing29,indent=0]
----
<1> Set the `GroupValidationStatusHandler` for the row editor
<2> Get the row-level validation status
<3> Get the single editor components validation status
<4> Get the row-level validation errors
<5> Get the single editor components validation errors

===== Listening to editor components value change

When a listing row is in edit mode, one ore more `ValueChangeListener` can be added to the editor input components to listen to value change, using the `withValueChangeListener` builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleListing.java[tag=listing30,indent=0]
----
<1> Add a value change listener for the `NAME` property

[[View]]
=== View components and forms

The link:{apidir}/com/holonplatform/vaadin/flow/components/ViewComponent.html[ViewComponent^] component can be used to display data, providing consistent formatting and style across the whole UI, including localization and *internationalization* support.

The `ViewComponent` API extends:

* `ValueHolder`: it handles a typed value. See <<ValueHolder>>.
* `HasComponent`: it can used as UI component. See <<HasComponent>>.

A `ViewComponent` instance can be created either using the `ViewComponent` API builder methods, providing the value type or the `Components` API, through the `Components.view` sub interface (see <<Components>>).

The `ViewComponent` builder API provides methods to configure the UI component, including methods to set a *localizable label* for the component and to add component click listeners.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc1,indent=0]
----
<1> Get a `String` type `ViewComponent` builder
<2> Set the component width to 100%
<3> Add a CSS style class name
<4> Set the label
<5> Set the label using a localizable message
<6> Set the description
<7> Add a click handler
<8> Set an initial value
<9> Add value change listener
<10> The previous value
<11> The changed value
<12> Direct `ViewComponent` creation method
<13> The `Components.view.component` method of the `Components` API can be used to create and configure a `ViewComponent`

A `ViewComponent` instance can be used as _value holder_ to handle the value to display (see <<ValueHolder>>).

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc2,indent=0]
----
<1> Create a `String` type `ViewComponent`
<2> Add the component to a layout using the `getComponent()` method
<3> Set the component value
<4> Get the component value
<5> Get the component optional value
<6> Clear the component value
<7> Check if the component is empty

==== Value conversion and formatting

A `ViewComponent` converts the value it holds to a `String` in order to display it in UI. For value conversion and formatting the `ViewComponent` API relies on the Holon Platform link:{coreapidir}/com/holonplatform/core/presentation/StringValuePresenter.html[StringValuePresenter^] API.

This ensures a consistent behaviour across the application on how the values are displayed and the current `LocalizationContext` is used, if available, to apply the proper internationalization conventions to format, for example, a numeric value.

See the link:holon-core.html#StringValuePresenter[StringValuePresenter API^] documentation for details.

To provide a custom value conversion logic, a value conversion function can be provided at  `ViewComponent` build time:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc3,indent=0]
----
<1> Create a `Integer` type `ViewComponent`, providing the function to convert the `Integer` value to `String`

==== Using the property value presenters

When a `Property` value has to be displayed, a `ViewComponent` can be created and bound to the  `Property` definition, inheriting the property value type as component type and enabling the link:{coreapidir}/com/holonplatform/core/property/PropertyValuePresenter.html[PropertyValuePresenter^] based strategy to convert and format the value in a consistent way across the application.

TIP: See the link:holon-core.html#Property.presentation[Property value presentation^] documentation for details on property value presentation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc4,indent=0]
----
<1> `Integer` type property definition
<2> Create a `ViewComponent` using the `MY_PROPERTY` property definition. The property value presenters will be used to convert the value to a `String` and apply formatting

This allows to *generalize the property value presentation* and make it consistent across all the application UI components which support property value presenters, including `Input` components (see <<Input>>) and listing components (see <<Listing>>).

New `PropertyValuePresenter` can be registered and used transparently to present the value for a specific type or a specific property configuration.

For example, suppose we want to add a `#` prefix to each value of the `MY_PROPERTY` property. We can declare a `PropertyValuePresenter` and bind it to the `MY_PROPERTY` property in the property presenters registry:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc5a,indent=0]
----
<1> Get the default `PropertyValuePresenterRegistry`
<2> Register a `PropertyValuePresenter`, bound to the `MY_PROPERTY` property, which adds a `#` prefix to the property value

From now on, any `ViewComponent` instance will use the new presenter to render the `MY_PROPERTY` property value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc5b,indent=0]
----
<1> The `ViewComponent` instance will use the new presenter to render the `MY_PROPERTY` property value
<2> Any other property presentation service will use the new presenter for the `MY_PROPERTY` property value. In this example, the `MY_PROPERTY` property is directly used to present the `1` value and the result will be the String `#1`.

[[ViewComponentAdapter]]
==== Create a `ViewComponent` from a generic `Component`

You can use the `ViewComponent` API `adapt` static methods to transform any `Component` into a `ViewComponent`. The `Component` will be used as `ViewComponent` content and a suitable function must be provided to setup the `Component` instance each time the value changes, for example to display the value using the custom `Component` instance.

A generic `Component` can be turn into a `ViewComponent` either providing:

*1.* The `Component` to use a `ViewComponent` content and a _consumer_ function to setup the `Component` instance each time the value changes:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc14,indent=0]
----
<1> A `Span` is used as `String` type `ViewComponent` content, setting the Span text with the provided value each time the `ViewComponent` value changes

*2.* A function to provided a custom `Component` instance each time the value changes, to be used as  `ViewComponent` content:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc15,indent=0]
----
<1> Each time the value changes, a new `RouterLink` is created and used as `ViewComponent` content

The `adapt` methods return a builder API consistent with the default `ViewComponent` builder API, allowing to configure the `ViewComponent` component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc16,indent=0]
----
<1> Create a `ViewComponent` which shows a `RouterLink` each time the value changes
<2> Set the component width to 100%
<3> Add a CSS style class name
<4> Set the label
<5> Set the label using a localizable message
<6> Set the description
<7> Add a click handler
<8> Set an initial value
<9> Add value change listener

[[ViewComponentPropertyRenderer]]
==== `ViewComponent` property renderer

When the `holon-vaadin-flow` artifact is in classpath, a default `PropertyRenderer` is automatically registered to render a `Property` as a `ViewComponent`.

TIP: See the link:holon-core.html#PropertyRenderer[Property renderering^] documentation for details about the property renderers architecture.

So the `ViewComponent.class` type can be used to render any property as a `ViewComponent`. In this scenario, the property *localizable message* is used if available as `ViewComponent` label.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc6,indent=0]
----
<1> Declare a boolean type property
<2> Set the property localizable message
<3> Create `ViewComponent` instance using the property renderer. The property localizable message will be used as `ViewComponent` label.

[[PropertyViewGroup]]
==== Organize view components in groups and forms

A set of `ViewComponent` type components can be grouped and organized using a link:{apidir}/com/holonplatform/vaadin/flow/components/PropertyViewGroup.html[PropertyViewGroup^], using the Holon Platform link:holon-core.html#Property[Property model^] to bind each `ViewComponent` to a property definition.

The property definitions will be used as *references* to get and configure the `ViewComponent` instances managed by the group and to *set the group values* to display using a `PropertyBox` type.

The `PropertyViewGroup` API provides method to inspect the available properties and the `ViewComponent` instances bound to each property. Through the `ValueHolder` API, the group value can be setted and managed (see <<ValueHolder>>).

To create a `PropertyViewGroup`, the *property set* to use must be provided at build time. Both the `PropertyViewGroup` API and the `Components` API (through the `Components.view` sub interface) can be used to obtain a property view group builder.

By default, the property rendering architecture is used to *automatically generate* the `ViewComponent` instances for each property of the group property set (see <<ViewComponentPropertyRenderer>>).

For example, given the following property model definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=propertydef,indent=0]
----

A `PropertyViewGroup` can be created in the following way:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc7,indent=0]
----
<1> Create a `PropertyViewGroup` using the `SUBJECT` property set. The `ViewComponent` for each property will be automatically generated using the property renderers
<2> Create a `PropertyViewGroup` from the `Components` API
<3> Get the group property set 
<4> Get the group `ViewComponent` elements
<5> Get the group bindings, i.e. the `ViewComponent` bound to each property
<6> Get the `ViewComponent` bound to the `NAME` property, if available
<7> Require the `ViewComponent` bound to the `NAME` property
<8> Set the group value using a `PropertyBox`: each property value available from the `PropertyBox` instance will be setted into the corresponding `ViewComponent`, if available
<9> Get the current group value
<10> Clear the group value
<11> Check whether the group is empty, i.e. has no value

To customize this behaviour and provide the `ViewComponent` to use for one or more property, the `PropertyViewGroup` builder API provides a set of `bind` methods, which can be use to explicitly bind a `ViewComponent` instance to a property. 

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc8,indent=0]
----
<1> Create a `PropertyViewGroup` using the `SUBJECT` property set
<2> Bind a `ViewComponent` instance to the `NAME` property
<3> Bind a `ViewComponent` instance to the `NAME` property using a function

===== Group configuration

The `PropertyViewGroup` builder API provides method to configure the group, allowing to:

* Hide one or more property: the hidden property won't be bound to a `ViewComponent`
* Add a _post processor_ to configure the `ViewComponent` instances just before the binding occurs
* Add group value change listeners

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc9,indent=0]
----
<1> Create a `PropertyViewGroup` using the `SUBJECT` property set
<2> Set the `ID` property as hidden
<3> Add a binding post processor
<4> Add a value change listener

[[PropertyViewForm]]
===== Using a `PropertyViewForm` to make the group a UI component

The `PropertyViewGroup` API handles a group of view components bound to a property set, but is it not a UI component itself. The link:{apidir}/com/holonplatform/vaadin/flow/components/PropertyViewForm.html[PropertyViewForm^] API can be used to provide a UI component for the group and use it as a _form_ in application UI.

A `PropertyViewGroup` extends the `HasComponent` interface to provide the actual group UI component  (see <<HasComponent>>) and the link:{apidir}/com/holonplatform/vaadin/flow/components/Composable.html[Composable^] API to declare the UI component to use as group elements container and the strategy to apply to organize the `ViewComponent` group elements into the group content area.

The `Composer` API can be used to implement the composition logic, i.e. to add the available `ViewComponent` elements to the UI component declared as group content. The `Composer` function provides:

* The group UI content element.
* A reference to the group API to obtain the `ViewComponent` elements (and the corresponding property bindings) to add to the group UI content element.

A default `Composer` for a `com.vaadin.flow.component.HasComponents` type UI element can be obtain using the `componentContainerComposer()` method of the `Composable` API. This composer adds the group elements sequentially to the `HasComponents` group content element, in the order they are provided from the group property set.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc10,indent=0]
----
<1> Create a `PropertyViewForm` using the `SUBJECT` property set, a `VerticalLayout` as group UI element
<2> The default component container composer is used
<3> The `getComponent()` method can be used to add the `PropertyViewForm` to a layout
<4> Set a form value

A set of convenience builder methods are available for the base Vaadin layouts:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc11,indent=0]
----
<1> Create a `PropertyViewForm` using the `SUBJECT` property set and a `VerticalLayout` as group UI element
<2> Create a `PropertyViewForm` using the `SUBJECT` property set and a `HorizontalLayout` as group UI element
<3> Create a `PropertyViewForm` using the `SUBJECT` property set and a `FormLayout` as group UI element

A custom `Composer` can be used to control and customize the group element composition strategy:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc12,indent=0]
----
<1> Provide a custom composition logic

===== Form configuration

A `PropertyViewForm` can be configured using the builder API in order to:

* Hide one or more property: the hidden property won't be bound to a `ViewComponent`
* Add an _initializer_ to configure the form UI content
* Add a _post processor_ to configure the `ViewComponent` instances just before the binding occurs
* Add form value change listeners
* Configure the property _captions_, i.e. to set the label to use for the `ViewComponent` bound to a property

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleViewComponent.java[tag=vc13,indent=0]
----
<1> Create a `PropertyViewForm` using the `SUBJECT` property set and a `FormLayout`
<2> Set the `ID` property as hidden
<3> Set the form content initializer
<4> Set the binding post processor
<5> Add a value change listener 
<6> Hide the `ID` property caption
<7> Set the localizable caption for the `NAME` property

[[Input]]
=== Input components and forms

The link:{apidir}/com/holonplatform/vaadin/flow/components/Input.html[Input^] API can be used to create UI components to handle *user input*, ensuring a consistent data type handling and input format patterns.

The `Input` API extends:

* `ValueHolder`: it handles a typed value. See <<ValueHolder>>.
* `HasComponent`: it can used as UI component. See <<HasComponent>>.

Furthermore, the `Input` API provides methods to set the UI component in *read only* mode and to display required indicators and validation errors.

A `Input` instance can be created either using the `Input` API builder methods, providing the value type,  or the `Components` API, through the `Components.input` sub interface (see <<Components>>).

The `Input` builder API provides methods to configure the UI component, including methods to set a localizable label for the component and a complete set of configuration methods according to the input value type.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input1,indent=0]
----
<1> Get a `String` type `Input` builder
<2> Set the width to 100%
<3> Add a CSS style class name
<4> Set the input label
<5> Set the input label using a localizable message
<6> Set the input description
<7> Set to treat blank values as `null` values. 
<8> Set the auto-capitalize mode
<9> Set the max characters count allowed for input
<10> Set the input placeholder using a localizable message
<11> Enable auto focus
<12> Set the prefix component
<13> Set the input tab index
<14> Set the input as read only, preventing the user from changing the input value
<15> Add a blur (focus lost) listener
<16> Add value change listener
<17> The previous value
<18> The changed value

A set of `Input` builders for the most common types are available both form the `Input` API and from the `Components.input` API.

Each `Input` is rendered using a suitable UI component according to the input value type. For example, a `TextField` is used for String type inputs and a `Checkbox` for boolean type inputs.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input2,indent=0]
----
<1> Create an `Input` for `String` type values
<2> Create an `Input` for `String` type values using a _text area_ to render the input component
<3> Create an `Input` for `Boolean` type values
<4> Create an `Input` for a numeric type value, a `Double` in this case
<5> Create an `Input` for `LocalDate` type values
<6> Create an `Input` for `LocalDateTime` type values
<7> Create an `Input` for `LocalTime` type values
<8> Create an `Input` for `Date` type values
<9> Create an `Input` for the given value type, if a suitable implementation is available

NOTE: The `Components.input` API provides the same methods to obtain the input builders.

A `Input` instance can be used as _value holder_ to handle the input value (see <<ValueHolder>>).

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input3,indent=0]
----
<1> Create a `String` type `Input`
<2> Add the input component to a layout using the `getComponent()` method
<3> Set the input value
<4> Get the input value
<5> Get the input optional value
<6> Clear the input value
<7> Check if the input is empty (i.e. has no value)
<8> Set the input as read only
<9> Check whether the input is read only
<10> Add a value change listener

[[InputPropertyRenderer]]
==== `Input` property renderer

When the `holon-vaadin-flow` artifact is in classpath, a default `PropertyRenderer` is automatically registered to render a `Property` as an `Input`.

TIP: See the link:holon-core.html#PropertyRenderer[Property renderering^] documentation for details about the property renderers architecture.

So the `Input.class` type can be used to render any property as a `Input`. In this scenario, the property *localizable message* is used if available as `Input` label.

The `Input` API makes available the `create(Property<T> property)` method to directly create an `Input` for a given property. 

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input4,indent=0]
----
<1> Declare a `Integer` type property
<2> Create a `Input` to handle the `MY_PROPERTY` property value using the `Input` API
<3> Create a `Input` to handle the `MY_PROPERTY` property value using the property renderer for the `Input` class

The property renderers architecture is used *consistently across the application UI*, so when a renderer is bound to a specific property condition it is used by all the UI components with property rendering support, including input groups/forms (see <<PropertyInputGroup>>) and item listing editors (see <<ItemListingEdit>>).

For example, suppose we want to use a custom `MyInput` class to render the `Input` component for the  `MY_PROPERTY` property definition. A custom property renderer can be created and registered:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input5,indent=0]
----
<1> Get the default `PropertyRendererRegistry`
<2> Register a `InputPropertyRenderer`, bound to the `MY_PROPERTY` property, to provide a `MyInput` instance

From now on, the `Input` component for the `MY_PROPERTY` property definition will be a `MyInput` instance.

[[InputValueConversion]]
==== Input value conversion

The `Input` API provides methods to use an `Input` with a different type than the value type to handle, providing a suitable `com.vaadin.flow.data.converter.Converter` to perform the value conversions to the required type.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input6,indent=0]
----
<1> Create a `String` type `Input`
<2> Create a `Integer` type `Input` from the previous one, providing the String to Integer and back converter

A Holon Platform `PropertyValueConverter` can also be use to provide the value conversion logic when the input is bound to a `Property` definition.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input7,indent=0]
----
<1> Create a `Integer` type `Input`
<2> Create a `Boolean` type `Input` for the `PROPERTY` property, using the previous input and a _numeric boolean_ `PropertyValueConverter`

[[InputAdapters]]
==== Input adapters for `HasValue` components

The `Input` API provides methods to _adapt_ a standard Vaadin `HasValue` type input component as an `Input`, including value conversion support using a `com.vaadin.flow.data.converter.Converter`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input8,indent=0]
----
<1> Create a `String` type `Input` from a `TextField`
<2> Create a `Integer` type `Input` from a `TextField`, providing the value converter

[[SelectInputs]]
==== Select type inputs

The link:{apidir}/com/holonplatform/vaadin/flow/components/SingleSelect.html[SingleSelect^] and link:{apidir}/com/holonplatform/vaadin/flow/components/MultiSelect.html[MultiSelect^] APIs are `Input` extensions which represent _selectable_ input components, i.e. input components which provide a *set of items* from which the input value can be selected, either supporting *single or multiple* selection values.

The `Input` API and the corresponding Components.input API provides methods to create `SingleSelect` and `MultiSelect` type input components, providing the *selectable value type*.

For `SingleSelect` input types, the input component can be rendered as:

* *Simple select*: a Vaadin `Select` component is used as input component.
* *Filterable select*: a Vaadin `ComboBox` component is used as input component.
* *Options select*: a `RadioButtonGroup` component is used as input component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input9,indent=0]
----
<1> Create a `String` type `SingleSelect` input
<2> Create a `String` type `SingleSelect` input using the _options_ rendering mode
<3> Create a `String` type `MultiSelect` input

The select input components can be used just like any other _value holder_ type component to set and get the selected item/s (see <<ValueHolder>>). The `MultiSelect` type input, since it allows multiple items selection, uses a `java.util.Set` to handle the input value.

NOTE: The `Components.input` API provides the same methods to obtain the select type input builders.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input10,indent=0]
----
<1> Set the input value, i.e. select the given value
<2> Get the input (selected) value
<3> Clear the input value (deselect any value)
<4> Check whether the input is empyt (no value is selected)
<5> Set the input values, i.e. select the given values, using a `Set`
<6> Get the input (selected) values as a `Set`

Besides the `Input` API, the selectable inputs implements the link:{apidir}/com/holonplatform/vaadin/flow/components/Selectable.html[Selectable^] API, which allows to manage and obtain the selected items.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input11,indent=0]
----
<1> Select given value
<2> Get the selected value
<3> Deselect any value

[[SelectDataSource]]
===== Select items data source

A select type `Input`, whether it's a `SingleSelect` or a `MultiSelect`, requires an *item set* to be configured, which represents the source for the selectable values. Only the available items will be used as valid selectable input values.

The builder API provides the `items` and `addItem` methods to provides the selection items set.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input12,indent=0]
----
<1> Add a selection item
<2> Add another selection item
<3> Set the selection items, replacing any previous item set

A standard Vaadin `DataProvider` can be used as items data source.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input13,indent=0]
----
<1> Use a `DataProvider` as items data source

When *the item type does not match the selection value type*, a link:{apidir}/com/holonplatform/vaadin/flow/data/ItemConverter.html[ItemConverter^] con be used to provide the item to selection value and back conversion logic.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input14,indent=0]
----
<1> Create a `String` type `SingleSelect` which uses a `MyBean` class as items type, providing a suitable `ItemConverter`
<2> Convert a `MyBean` type item into a `String` type selection value
<3> Convert a `String` type selection value into a `MyBean` type item

[[SelectPropertyDataSource]]
===== Use the `Datastore` API as items data source

When the property model is used to build a select type input, *the selection items are represented using the `PropertyBox` type by default*, and the property which represents the selection value has to be declared a construction time. 

The select input type will match the *selection property type* and the value provided as selection value will be obtained using the selection property definition from the `PropertyBox` type item instances.

For example, given the following property model definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=propertydef,indent=0]
----

A `SingleSelect` to select the `ID` property can be created as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input15,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property: the select input type will be `Long` like the property type
<2> Add a `PropertyBox` type selection item

When a property model bound select is used, the most simple and powerful way to provided the selection items is to use a `Datastore` as data source. The `Datastore` API makes easy and straightful to bind the select input to a backend data source.

When a `Datastore` is used, a `DataTarget` definition is required to declare the data model _entity_ to use as items data source (for example a RDBMS table name, or a collection name in a document based database).

A `Datastore` based data source can be configured using a standard DataProvider, through the `DatastoreDataProvider` API: see the <<DatastoreIntegration>> section to learn how to create and configure a `Datastore` based `DataProvider`.

Furthermore, the select input builder APIs provides convenience methods to set and configure a data source using a `Datastore`.

By default, *only the selection property is used as items property set*. To specify a different property set (i.e. a different query projection), the property set must be provided at data source configuration time.

For example, given the following `DataTarget` definition;

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=target,indent=0]
----

The select of the previous example can be configured as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input16,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property
<2> Use a `Datastore` as items data source, providing the `DataTarget` to use
<3> Declare to use the `SUBJECT` property set as items property set (hence as query projection)

The `Datastore` based data source can be configured, for example to *add query filters and sorts*. The configuration methods provided by the builder API corresponds to the ones provided by the `DatastoreDataProvider` API. See <<DatastoreQueryConfiguration>> for details.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input17,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property
<2> Use a `Datastore` as items data source, providing the `DataTarget` to use
<3> Add a fixed query filter
<4> Add a fixed query sort
<5> Add a `QueryConfigurationProvider` reference to provide dynamic query filters and sorts

[[FilterableSelect]]
===== Filterable select inputs

When a `SingleSelect` in the *filterable select* mode is used, since it is rendered using a `ComboBox` component, the selection items to select can be _suggested_ by the input component, *using the user input to filter the items set*.

When a standard `DataProvider` is used, the `filteringBy*` methods can be used to provide the items filtering strategy.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input18,indent=0]
----
<1> Create a `String` type `SingleSelect`
<2> Use a `DataProvider` as items data source
<3> Set the filtering mode, in this case checking whether the item value starts with the query value

When a `Datastore` based data source is used (see <<SelectPropertyDataSource>>), a function can be configured to transform the text typed by the user into the `QueryFilter` to add to the Datastore query to filter the returned items.

The filter converter function can be configured either using:

*1.* The `dataSource` builder method version which accepts the filter converter function:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input19,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property
<2> Use a `Datastore` as items data source, providing the `DataTarget` to use 
<3> Provide the function to convert the user typed text value to a `QueryFilter`
<4> Use the `SUBJECT` property set as items property set

*1.* The `filterConverter` builder method:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input19b,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property
<2> Use a `Datastore` as items data source, providing the `DataTarget` to use and `SUBJECT` as items property set
<3> Provide the function to convert the user typed text value to a `QueryFilter`

[[EnumSelect]]
===== Use select inputs with enumerations

The `Input` API and the `Components.input` API provides convenience methods to create *enumeration* based select inputs, automatically adding all the available enumeration values to the selection items set.

A `enum` type select can be created both as a `SingleSelect` and as `MultiSelect`.

For example, given the following `enum` class:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=enum1,indent=0]
----

A select type input for the enumeration values can be created as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input20,indent=0]
----
<1> Create a `SingleSelect` for the `MyEnum` enumeration
<2> Create a `SingleSelect` for the `MyEnum` enumeration using the _options_ rendering mode
<3> Create a `MultiSelect` for the `MyEnum` enumeration

The link:{coreapidir}/com/holonplatform/core/i18n/Caption.html[Caption^] annotation can be used on the enumeration class values to configure the select items _caption_, with localizable messages support.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=enum2,indent=0]
----

See the next section to learn how to configure the select items caption using the select input builder API.

[[SelectionItemsCaption]]
===== Selection items caption

By default, the selectable items are displayed in UI *using the `toString()` representation of the item itself*.

To change this behaviour, the item _captions_ can be configured either setting them explicitly using the builder API (through the `itemCaption` method), or using a `ItemCaptionGenerator` function to provide the caption for each selection item.

Example using explicit item captions:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input21,indent=0]
----
<1> Create a `Integer` type `SingleSelect`
<2> Set the `1` item caption
<3> Set the `2` item caption using a localizable message

Example using a `ItemCaptionGenerator`:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input22,indent=0]
----
<1> Create a `SingleSelect` using the `ID` selection property
<2> Use `SUBJECT` as items property set, which includes the `NAME` property
<3> Set the `ItemCaptionGenerator`: the `NAME` property value is used as item caption

For `Property` bound selectable inputs, a convenience `itemCaptionProperty` builder method is available to provide the property to use to obtain the item value which will be used as items caption.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input22b,indent=0]
----
<1> Create a `SingleSelect` using the `ID` selection property
<2> Use `SUBJECT` as items property set, which includes the `NAME` property
<3> The `NAME` property value is used as item caption

[[InputAdapterExtension]]
==== Extend the Input API using adapters

The `Input` API can be extended using custom _adapters_, i.e. a class/interface to provide additional Input attributes and/or functionalities.

An adapter can be registered at `Input` build time using the `withAdapter` method, providing:

* The adapter `Class`
* A `Function` to provide the adapter instance when requested, with the `Input` instance as function argument.

An adapter instance can be obtained using the `Input` API method `<A> Optional<A> as(Class<A> type)`. If an adapter of the given `type` is available (i.e. was registered as described above), the adapter function will be invoked to provide the adapter instance.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input38,indent=0]
----
<1> Register and adapter for the `MyExtension` type
<2> Get the `MyExtension` type instance, if available

[[ValidatableInput]]
==== Validatable inputs

The value of any `Input` component can be *validated* using the standard Holon Platform link:holon-core.html#Validator[Validator^] API, through the link:{apidir}/com/holonplatform/vaadin/flow/components/ValidatableInput.html[ValidatableInput^] API.

An `Input` can be made _validatable_, adding support for `Validator` registration, using:

*1.* The `validatable` builder method:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input23,indent=0]
----
<1> Make the input validatable
<2> Add a input value `Validator`
<3> Set whether to automatically validate the input value when it changes

*2.* The `ValidatableInput` adapter:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input24,indent=0]
----
<1> Use the `ValidatableInput` builder method to create and configure a validatable input from a standard `Input`
<2> Add a input value `Validator`
<3> Use the `ValidatableInput` _from_ method to directly create a validatable input from a standard `Input`
<4> Add a input value `Validator` using the `addValidator` method

A `ValidatableInput` extends the link:{apidir}/com/holonplatform/vaadin/flow/components/Validatable.html[Validatable^] API, which provides method to *validate the input value* using the registered validators.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input25,indent=0]
----
<1> Create a `ValidatableInput`
<2> Check whether the input value is valid
<3> Validate the input value, throwing a `ValidationException` if the validation fails
<4> Get the input value only if it is valid

By default, the *validation errors* are notified to the user using the UI component error message, if supported by the concrete input component.

The validation errors notification strategy can be customized using a `ValidationStatusHandler` function. The validation event provides the validation status (valid, invalid or unresolved) and the current validation errors, if any. 

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input26,indent=0]
----
<1> Set the `ValidationStatusHandler` to use for the `ValidatableInput`

TIP: the link:{apidir}/com/holonplatform/vaadin/flow/components/Validatable.html[Validatable^] API provides a set of `adapt` methods to use a Vaadin `com.vaadin.flow.data.binder.Validator` as a Holon Platform `Validator`.

[[PropertyInputGroup]]
==== Organize `Input` components in groups and forms

A set of `Input` components can be grouped and organized using a link:{apidir}/com/holonplatform/vaadin/flow/components/PropertyInputGroup.html[PropertyInputGroup^], using the Holon Platform link:holon-core.html#Property[Property model^] to bind each `Input` to a property definition.

The property definitions will be used as *references* to get and configure the `Input` instances managed by the group and to *get and set the group values* using a `PropertyBox` type.

The `PropertyInputGroup` API provides method to inspect the available properties and the `Input` instances bound to each property. Through the `ValueHolder` API, the group value can be setted and managed (see <<ValueHolder>>).

When a `PropertyBox` type value is setted for the group, each `Input` value bound to a property is setted according to the property value provided by the `PropertyBox` instance, if available.

When a the group value is obtained using the `getValue()` method, the current `Input` values are reflected into the `PropertyBox` instance, using the property to which each `Input` is bound.

To create a `PropertyInputGroup`, the *property set* to use must be provided at build time. Both the `PropertyInputGroup` API and the `Components` API (through the `Components.input` sub interface) can be used to obtain a `PropertyInputGroup` builder.

By default, the property rendering architecture is used to *automatically generate* the `Input` components for each property of the group property set (see <<InputPropertyRenderer>>).

For example, given the following property model definition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=propertydef,indent=0]
----

A `PropertyInputGroup` can be created in the following way:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input27,indent=0]
----
<1> Create a `PropertyInputGroup` using the `SUBJECT` property set. The `Input` for each property will be automatically generated using the property renderers
<2> Create a `PropertyInputGroup` from the `Components` API
<3> Get the group property set 
<4> Get the group `Input` elements
<5> Get the group bindings, i.e. the `Input` bound to each property
<6> Get the `Input` bound to the `NAME` property, if available
<7> Require the `Input` bound to the `NAME` property
<8> Set the group value using a `PropertyBox`: each property value available from the `PropertyBox` instance will be setted into the corresponding `Input`, if available
<9> Get the current group value: the current `Input` values (which in the meanwhile could have been changed by the user) are updated into the `PropertyBox` instance, according to the property to which each `Input` is bound
<10> Clear the group value
<11> Check whether the group is empty, i.e. has no value

To customize this behaviour and provide the `Input` component to use for one or more property, the `PropertyInputGroup` builder API provides a set of `bind` methods, which can be use to explicitly bind a `Input` instance to a property. 

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input28,indent=0]
----
<1> Create a `PropertyInputGroup` using the `SUBJECT` property set
<2> Bind a `Input` instance to the `NAME` property
<3> Bind a `Input` instance to the `NAME` property using a function

===== Input group configuration

The `PropertyInputGroup` builder API provides method to configure the group, allowing to:

* Hide one or more property: the hidden property won't be bound to a `Input`
* Add a _post processor_ to configure the `Input` instances just before the binding occurs
* Provide a *default value* for one or more `Input` components
* Add group value change listeners

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input29,indent=0]
----
<1> Create a `PropertyInputGroup` using the `SUBJECT` property set
<2> Set the `ID` property as hidden
<3> Set the default value supplier for the `NAME` property
<4> Add a binding post processor
<5> Add a value change listener

[[PropertyInputForm]]
===== Using a `PropertyInputForm` to make the group a UI component

The `PropertyInputForm` API handles a group of `Input` components bound to a property set, but it is not a UI component itself. The link:{apidir}/com/holonplatform/vaadin/flow/components/PropertyInputForm.html[PropertyInputForm^] API can be used to provide a UI component for the group and use it as a _form_ in application UI.

A `PropertyInputForm` extends the `HasComponent` interface to provide the actual group UI component  (see <<HasComponent>>) and the link:{apidir}/com/holonplatform/vaadin/flow/components/Composable.html[Composable^] API to declare the UI component to use as group elements container and the strategy to apply to organize the `Input` group elements into the group content area.

The `Composer` API can be used to implement the composition logic, i.e. to add the available `ViewComponent` elements to the UI component declared as group content. The `Composer` function provides:

* The group UI content element.
* A reference to the group API to obtain the `Input` elements (and the corresponding property bindings) to add to the group UI content element.

A default `Composer` for a `com.vaadin.flow.component.HasComponents` type UI element can be obtain using the `componentContainerComposer()` method of the `Composable` API. This composer adds the group elements sequentially to the `HasComponents` group content element, in the order they are provided from the group property set.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input30,indent=0]
----
<1> Create a `PropertyInputForm` using the `SUBJECT` property set, a `VerticalLayout` as group UI element
<2> The default component container composer is used
<3> The `getComponent()` method can be used to add the `PropertyInputForm` to a layout
<4> Set a form value

A set of convenience builder methods are available for the base Vaadin layouts:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input31,indent=0]
----
<1> Create a `PropertyInputForm` using the `SUBJECT` property set and a `VerticalLayout` as group UI element
<2> Create a `PropertyInputForm` using the `SUBJECT` property set and a `HorizontalLayout` as group UI element
<3> Create a `PropertyInputForm` using the `SUBJECT` property set and a `FormLayout` as group UI element

A custom `Composer` can be used to control and customize the group element composition strategy:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input32,indent=0]
----
<1> Provide a custom composition logic

===== Form configuration

A `PropertyInputForm` can be configured using the builder API in order to:

* Hide one or more property: the hidden property won't be bound to a `Input`
* Add an _initializer_ to configure the form UI content
* Add a _post processor_ to configure the `Input` instances just before the binding occurs
* Add form value change listeners
* Configure the property _captions_, i.e. to set the label to use for the `Input` bound to a property

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input33,indent=0]
----
<1> Create a `PropertyInputForm` using the `SUBJECT` property set and a `FormLayout`
<2> Set the `ID` property as hidden
<3> Set the form content initializer
<4> Set the binding post processor
<5> Add a value change listener 
<6> Hide the `ID` property caption
<7> Set the localizable caption for the `NAME` property

===== Input group and form validation

The `PropertyInputGroup` and the `PropertyInputForm` APIs provides `Input` validation support using the standard Holon Platform link:holon-core.html#Validator[Validator^] API. The value validation is supported:

* At *property level*, to validate the single `Input` value for each property.
* At *group level*, to validate the overall `PropertyBox` type group value.

The validators can be added using the `PropertyInputGroup` and the `PropertyInputForm` builder APIs.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input34,indent=0]
----
<1> Create a `PropertyInputForm` using the `SUBJECT` property set
<2> Add a validator for the `Input` component bound to the `NAME` property
<3> Add a group value validator
<4> Set whether to validate the `Input` values when each `Input` value changes

The `PropertyInputGroup` and the `PropertyInputForm` APIs provides a set of methods to perform the group/form validation, a part of which is inherited from the link:{apidir}/com/holonplatform/vaadin/flow/components/Validatable.html[Validatable^] API.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input35,indent=0]
----
<1> Check whether the form is valid
<2> Validate the form, firing both property level and group level validators
<3> Get the form value, returning an empty `Optional` if validation fails
<4> By default, when the form value is requested, the form validation is performed
<5> Get the form value skipping validation

===== Input groups validation status handler

By default, for the `PropertyInputGroup` and the `PropertyInputForm` components, the validation errors originated by the registered validators are notified to the user in the following way:

* For *property level* validators, if the `Input` component supports error messages notification (using the Vaadin `HasValidation` interface), the validation errors are setted as component errors.

* For *group level* validators, a `Dialog` is used to notify the validation errors.

The validation status errors notification can be customized using the link:{apidir}/com/holonplatform/vaadin/flow/components/ValidationStatusHandler.html[ValidationStatusHandler^] interface, both at property and group level.

The `ValidationStatusHandler` validation event provides the validation status (valid, invalid or unresolved) and the current validation errors, if any. 

To customize both the *property level* and the *group level* validation status notification, the `validationStatusHandler` builder method can be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input36,indent=0]
----
<1> Set a custom group level validation status handler
<2> Set a custom property level validation status handler for the `NAME` property

Furthermore, the link:{apidir}/com/holonplatform/vaadin/flow/components/GroupValidationStatusHandler.html[GroupValidationStatusHandler^] interface can be used to override all the validation status notification, customizing both the property level and the group level validation status notification using a single handler.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleInput.java[tag=input37,indent=0]
----
<1> Set the `GroupValidationStatusHandler` for the form
<2> Get the group level validation status
<3> Get the single `Input` validation status
<4> Get the group level validation errors
<5> Get the single `Input` validation errors

[[VaadinSessionScope]]
== Vaadin session scope

When the `holon-vaadin-flow` artifact is in classpath, a Holon Platform link:holon-core.html#Context[Context^] _scope_ bound to the current *Vaadin session* is automatically registered and available to manage context resources.

The link:{apidir}/com/holonplatform/vaadin/flow/VaadinSessionScope.html[VaadinSessionScope^] API can be used to obtain the *scope name*. The `VaadinSessionScope` API also provides convenience methods to access the Vaadin session scope.

The Vaadin session *attributes* are used as context resource registry and the a current `VaadinSession` must be available in order for the scope to work.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleSessionScope.java[tag=scope1,indent=0]
----
<1> Get the session scope using the scope name
<2> Get the session scope using the `VaadinSessionScope` API
<3> Require the session scope using the `VaadinSessionScope` API

For example, if a `LocalizationContext` is bound to the current Vaadin session using a session attribute, it can be retrieved using the standard Holon Platform `Context` API.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleSessionScope.java[tag=scope2,indent=0]
----
<1> Bind a `LocalizationContext` instance to the current Vaadin session attribute
<2> The `LocalizationContext` instance is now available as a context resource
<3> The `getCurrent()` method will return the `LocalizationContext` instance

[[DeviceInfo]]
== Device information

The link:{apidir}/com/holonplatform/vaadin/device/DeviceInfo.html[DeviceInfo^] API can be used to obtain information about the client device in which application is running.

A `DeviceInfo` instance is bound to each application `UI` and can be obtained using the `get()` API methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDeviceInfo.java[tag=di1,indent=0]
----
<1> Get the `DeviceInfo` bound to the given UI
<2> Get the `DeviceInfo` bound to the current UI
<3> Require the `DeviceInfo` bound to the current UI
<4> Get the current request `Accept` header
<5> Get the current request `User-Agent` header
<6> Get the device viewport width
<7> Get the device viewport height
<8> Check if the device is a smartphone
