[[VaadinFlowComponents]]
== Vaadin Flow UI components

The `holon-vaadin-flow` artifact is the main entry point to enable the Holon platform Vaadin Flow integration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow</artifactId>
<version>{revnumber}</version>
----

It provides integration between the Vaadin Flow core architecture and the Holon Platform one, providing also a set of UI components specifically designed to ensure a seamless integration with the Holon Platform Property model, Datastore API, authentication and internationalization APIs.

[[DatastoreIntegration]]
=== Datastore API integration

The Holon Platform link:holon-core.html#Datastore[Datastore API^] can be used to bind a UI component to backend data in a simple and powerful way, relying on the Holon Platform link:holon-core.html#Property[Property model^] to represent the underlying data model.

The link:{apidir}/com/holonplatform/vaadin/flow/data/DatastoreDataProvider.html[DatastoreDataProvider^] API is a standard Vaadin Flow `com.vaadin.flow.data.provider.DataProvider` which uses the `Datastore` API to fetch data from backend and makes available a set of configuration methods to control and setup the queries to perform.

Since it is a standard `DataProvider`, it can be seamlessy used in any Vaadin UI component which support data binding.

The `DatastoreDataProvider` provides a set of `create(..)` and `builder(..)` methods to build and configure a new `Datastore` based `DataProvider`. At least the following elements are required to create a `DatastoreDataProvider`:

* The reference to the `Datastore` instance to use.
* A `DataTarget` declaration, which represents the data model _entity_ to use as data source (for example, a RDBMS table name).

==== Item types

By default, the Holon Platform link:holon-core.html#Property[Property model^] is used to represent the backend data model attributes, and the link:holon-core.html#PropertyBox[PropertyBox^] type to represent a data source _item_, intended as a collection of properties and their values.

So, besides the `Datastore` reference and the `DataTarget` definition, the *property set* to use has to be provided to the `DatastoreDataProvider` builder methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider1,indent=0]
----
<1> Property set declaration
<2> Data target definition
<3> Datastore reference
<4> Create a new `DatastoreDataProvider` using the `SUBJECT` property set
<5> Create a new `DatastoreDataProvider` providing the `ID` and `NAME` properties as property set

Furthermore, the `DatastoreDataProvider` API provides methods to use a *bean class* as item type. The item property set is obtained form the bean class attributes, using the bean property names as property set property names.

TIP: See the link:holon-core.html#Beans[Java Beans and property model^] documentation section for information about the conventions and the configuration options which can be used when a Java Bean is used with the Holon Platform property model.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider2,indent=0]
----
<1> Data target definition
<2> Datastore reference
<3> Create a new `DatastoreDataProvider` using the `MyBean` class as item type

==== Filter types

By default, the `QueryFilter` type is used used as data provider filter type, since it is the default property model representation for the `Datastore` API query restrictions definition.

To use a different data provider filter type, a *filter converter function* can be configured for the `DatastoreDataProvider`, to provide the custom filter type to `QueryFilter` type conversion logic.

In the example below, a `String` type filter is used and the conversion function creates a `QueryFilter` which represents the condition "The `NAME` data model attribute value starts with the given filter value":

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider3,indent=0]
----

Similarly when a bean item type is used:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider4,indent=0]
----

==== Custom item and filter type

The `DatastoreDataProvider` API makes also available methods to customize both the item type and the data provider filter type, providing:

* The `PropertyBox` type to the custom item type conversion function.
* The custom filter type to the `QueryFilter` type conversion function.

For example, using a `MyItem` item class and a `String` filter type:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider5,indent=0]
----
<1> The `SUBJECT` property set is used as query projection
<2> Item conversion function: from the `PropertyBox` type object to the `MyItem` item type
<3> Filter conversion function: from a `String` type filter to a `QueryFilter` type

==== `Datastore` Query configuration

The queries performed by the `Datastore` to fetch the data from backend can be configured using the `DatastoreDataProvider` *builder API*.

===== Query filters and sorts

The query filters and sorts can be configured in two ways:

*1. At construction time, using the appropriate builder methods:* 

The `DatastoreDataProvider` builder API provide methods to:

* Add one or more `QueryFilter` to the query definition. These filters will always be included in the query execution.
* Add one or more `QuerySort` to the query definition. These sorts will always be included in the query execution.
* Set a default `QuerySort`, which will be used when no other sort is configured for the query.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider6,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a query filter
<3> Add a query sort
<4> Set the default query sort

*2. Dynamically, using a `QueryConfigurationProvider`:* 

One or more `QueryConfigurationProvider` references can be configured for the query using the `DatastoreDataProvider` builder API. 

At each query execution, the `getQueryFilter()` and `getQuerySort()` methods of each available `QueryConfigurationProvider` will be invoked to obtain the filters and sorts to add to the query, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider7,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a `QueryConfigurationProvider`
<3> At each query execution, this method will be invoked to obtain the query filters, if any
<4> At each query execution, this method will be invoked to obtain the query sorts, if any

===== `QuerySortOrder` conversion

When the standard Vaadin Flow `com.vaadin.flow.data.provider.QuerySortOrder` type is used for the data provider query configuration, the `DatastoreDataProvider` can be configured to control how a `QuerySortOrder` declaration is converted into a `QuerySort` definition.

For this purpose, the `DatastoreDataProvider` builder API allows to configure a `QuerySortOrder` conversion function.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider8,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Set the `QuerySortOrder` conversion function

===== Item identifier

By default, the item itself is used as _item identifier_ to discern each item from another within the query results. The item identification relies on the standard Java `equals` and `hashCode` object methods.

When a `PropertyBox` type item is used, the default item identification strategy relies on the property set *identifier properties* values, if declared.

TIP: See the link:holon-core.html#IdentifierProperties[Identifier properties^] documentation section for details.

If a custom item identifier should be used, an item identifier provider function can be configured using the `DatastoreDataProvider` builder API. This function must provide the item identifier for each item obtained form query execution.

.Example using a PropertyBox type item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider9,indent=0]
----
<1> Set an item identifier provider function which provides the `ID` property value as item identifier

.Example using a bean item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider10,indent=0]
----
<1> Set an item identifier provider function which provides the bean id value as item identifier using the `getId()` method

==== Setup a `Datastore` data provider using builders

The Holon Platform Vaadin Flow module _builder_ APIs provides covenient methods to setup a `Datastore` based data provider for UI components which support data binding.

Example for a _single select_, implemented using a Vaadin `ComboBox` component:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=builder,indent=0]
----

See <<Components>> to learn about the available component builders.

[[I18n]]
=== Internationalization

TBD


[[Components]]
=== Component builders and providers

The link:{apidir}/com/holonplatform/vaadin/flow/components/Components.html[Components^] API is *the main entry point* to build and configure the UI components.

It provides a complete set of methods to obtain _fluent_ builders to create and configure both standard Vaadin Flow components and the additional UI components provided by the Holon Platform Vaadin Flow module.

==== Component builders structure

Each component builder API is composed by a set of specific builders, each related to a specific feature of the component. The feature builders are independent from the specific UI component to build, thus providing a common API which makes component configuration simple and intuitive.

For example, the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasTextConfigurator.html[HasTextConfigurator^] represents a builder part for UI components which supports a _text_, and it is included in any builder for UI components with text support.

Similarly, the the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasSizeConfigurator.html[HasSizeConfigurator^] API is included in component builders which supports the component _size_ configuration.

This ensures a consistent and common API to build and configure any UI component.

In the example below, the `HasTextConfigurator` and the `HasSizeConfigurator` are used in the same way to configure a _label_ and a _button_ component text and size:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=builders1,indent=0]
----
<1> Get a _label_ component builder
<2> Set the label text (using the `HasTextConfigurator` API)
<3> Set the label width (using the `HasSizeConfigurator` API)
<4> Get a _button_ component builder
<5> Set the button text (using the `HasTextConfigurator` API)
<6> Set the button width (using the `HasSizeConfigurator` API)

[[BaseBuilders]]
==== Base components builders

TBD

[[BaseConfigurators]]
==== Base components configurators

TBD


[[Listing]]
=== List data in grids

TBD

[[View]]
=== View components and forms

TBD

[[Input]]
=== Input components and forms

TBD

[[Dialogs]]
=== Dialogs

TBD

[[PropertyRenderers]]
=== Property renderers for UI components

TBD

[[VaadinSessionScope]]
== Vaadin session scope

TBD

[[DeviceInfo]]
=== Device information

TBD




