[[VaadinFlowComponents]]
== Vaadin Flow UI components

The `holon-vaadin-flow` artifact is the main entry point to enable the Holon platform Vaadin Flow integration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow</artifactId>
<version>{revnumber}</version>
----

It provides integration between the Vaadin Flow core architecture and the Holon Platform one, providing also a set of UI components specifically designed to ensure a seamless integration with the Holon Platform Property model, Datastore API, authentication and internationalization APIs.

[[DatastoreIntegration]]
=== Datastore API integration

The Holon Platform link:holon-core.html#Datastore[Datastore API^] can be used to bind a UI component to backend data in a simple and powerful way, relying on the Holon Platform link:holon-core.html#Property[Property model^] to represent the underlying data model.

The link:{apidir}/com/holonplatform/vaadin/flow/data/DatastoreDataProvider.html[DatastoreDataProvider^] API is a standard Vaadin Flow `com.vaadin.flow.data.provider.DataProvider` which uses the `Datastore` API to fetch data from backend and makes available a set of configuration methods to control and setup the queries to perform.

Since it is a standard `DataProvider`, it can be seamlessy used in any Vaadin UI component which support data binding.

The `DatastoreDataProvider` provides a set of `create(..)` and `builder(..)` methods to build and configure a new `Datastore` based `DataProvider`. At least the following elements are required to create a `DatastoreDataProvider`:

* The reference to the `Datastore` instance to use.
* A `DataTarget` declaration, which represents the data model _entity_ to use as data source (for example, a RDBMS table name).

==== Item types

By default, the Holon Platform link:holon-core.html#Property[Property model^] is used to represent the backend data model attributes, and the link:holon-core.html#PropertyBox[PropertyBox^] type to represent a data source _item_, intended as a collection of properties and their values.

So, besides the `Datastore` reference and the `DataTarget` definition, the *property set* to use has to be provided to the `DatastoreDataProvider` builder methods.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider1,indent=0]
----
<1> Property set declaration
<2> Data target definition
<3> Datastore reference
<4> Create a new `DatastoreDataProvider` using the `SUBJECT` property set
<5> Create a new `DatastoreDataProvider` providing the `ID` and `NAME` properties as property set

Furthermore, the `DatastoreDataProvider` API provides methods to use a *bean class* as item type. The item property set is obtained form the bean class attributes, using the bean property names as property set property names.

TIP: See the link:holon-core.html#Beans[Java Beans and property model^] documentation section for information about the conventions and the configuration options which can be used when a Java Bean is used with the Holon Platform property model.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider2,indent=0]
----
<1> Data target definition
<2> Datastore reference
<3> Create a new `DatastoreDataProvider` using the `MyBean` class as item type

==== Filter types

By default, the `QueryFilter` type is used used as data provider filter type, since it is the default property model representation for the `Datastore` API query restrictions definition.

To use a different data provider filter type, a *filter converter function* can be configured for the `DatastoreDataProvider`, to provide the custom filter type to `QueryFilter` type conversion logic.

In the example below, a `String` type filter is used and the conversion function creates a `QueryFilter` which represents the condition "The `NAME` data model attribute value starts with the given filter value":

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider3,indent=0]
----

Similarly when a bean item type is used:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider4,indent=0]
----

==== Custom item and filter type

The `DatastoreDataProvider` API makes also available methods to customize both the item type and the data provider filter type, providing:

* The `PropertyBox` type to the custom item type conversion function.
* The custom filter type to the `QueryFilter` type conversion function.

For example, using a `MyItem` item class and a `String` filter type:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider5,indent=0]
----
<1> The `SUBJECT` property set is used as query projection
<2> Item conversion function: from the `PropertyBox` type object to the `MyItem` item type
<3> Filter conversion function: from a `String` type filter to a `QueryFilter` type

==== `Datastore` Query configuration

The queries performed by the `Datastore` to fetch the data from backend can be configured using the `DatastoreDataProvider` *builder API*.

===== Query filters and sorts

The query filters and sorts can be configured in two ways:

*1. At construction time, using the appropriate builder methods:* 

The `DatastoreDataProvider` builder API provide methods to:

* Add one or more `QueryFilter` to the query definition. These filters will always be included in the query execution.
* Add one or more `QuerySort` to the query definition. These sorts will always be included in the query execution.
* Set a default `QuerySort`, which will be used when no other sort is configured for the query.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider6,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a query filter
<3> Add a query sort
<4> Set the default query sort

*2. Dynamically, using a `QueryConfigurationProvider`:* 

One or more `QueryConfigurationProvider` references can be configured for the query using the `DatastoreDataProvider` builder API. 

At each query execution, the `getQueryFilter()` and `getQuerySort()` methods of each available `QueryConfigurationProvider` will be invoked to obtain the filters and sorts to add to the query, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider7,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Add a `QueryConfigurationProvider`
<3> At each query execution, this method will be invoked to obtain the query filters, if any
<4> At each query execution, this method will be invoked to obtain the query sorts, if any

===== `QuerySortOrder` conversion

When the standard Vaadin Flow `com.vaadin.flow.data.provider.QuerySortOrder` type is used for the data provider query configuration, the `DatastoreDataProvider` can be configured to control how a `QuerySortOrder` declaration is converted into a `QuerySort` definition.

For this purpose, the `DatastoreDataProvider` builder API allows to configure a `QuerySortOrder` conversion function.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider8,indent=0]
----
<1> Get a `DatastoreDataProvider` builder 
<2> Set the `QuerySortOrder` conversion function

===== Item identifier

By default, the item itself is used as _item identifier_ to discern each item from another within the query results. The item identification relies on the standard Java `equals` and `hashCode` object methods.

When a `PropertyBox` type item is used, the default item identification strategy relies on the property set *identifier properties* values, if declared.

TIP: See the link:holon-core.html#IdentifierProperties[Identifier properties^] documentation section for details.

If a custom item identifier should be used, an item identifier provider function can be configured using the `DatastoreDataProvider` builder API. This function must provide the item identifier for each item obtained form query execution.

.Example using a PropertyBox type item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider9,indent=0]
----
<1> Set an item identifier provider function which provides the `ID` property value as item identifier

.Example using a bean item
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=dataprovider10,indent=0]
----
<1> Set an item identifier provider function which provides the bean id value as item identifier using the `getId()` method

==== Setup a `Datastore` data provider using builders

The Holon Platform Vaadin Flow module _builder_ APIs provides covenient methods to setup a `Datastore` based data provider for UI components which support data binding.

Example for a _single select_, implemented using a Vaadin `ComboBox` component:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDatastore.java[tag=builder,indent=0]
----

See <<Components>> to learn about the available component builders.

[[I18n]]
=== Internationalization

The Holon Platform Vaadin Flow module provides a complete integration with the Holon Platform link:holon-core.html#i18n[internationalization^] architecture, making UI components and messages localization simple and conistent with the full application stack.

Each localizable messages is represented by:

* A required *message code*, i.e. the `String` key to be used to obtain the message localization for a given `Locale`.
* An optional *default message*, to be used if a localized message is not available for a `Locale`.
* A set of optional *localization arguments*, which can be used to replace a specific _placeholder_ with the actual values.

The localizable message attributes described above can be declared and represented using the link:{coreapidir}/com/holonplatform/core/i18n/Localizable.html[Localizable^] interface, which provides convenient methods to create `Localizable` instances providing the message localization attributes.

The UI component builders which allow to setup localizable messages and texts, always support the `Localizable` API to provide the message localization attributes, providing also convenient methods to directly set the message localization attributes.

Example using a _button_ component builder:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=builder1,indent=0]
----
<1> Set the button text using a not localizable message
<2> Set the button text using a localizable message, providing the default message and the localization code
<3> Set the button text using a localizable message, also providing two message localization arguments 
<4> Set the button text using a `Localizable` reference

See <<Components>> to learn about the available component builders.

==== LocalizationContext and LocalizationProvider

The Holon Platform internationalization support relies on the link:holon-core.html#LocalizationContext[LocalizationContext^] API, which acts as message resolver, localized data formatter and holder for the current user `Locale`.

In order for the UI components localization to work, one of the following conditions must be met:

* A `LocalizationContext` is available as _context_ resource and a `Locale` is configured. See the Holon Platform link:holon-core.html#Context[Context^] architecture for information about the context resources management.

* Otherwise, a Vaadin Flow `I18NProvider` is available from the current Vaadin Service.

TIP: See <<VaadinSessionScope>> to learn about the _context scope_ for resources bound to the current Vaadin application session.

The link:{apidir}/com/holonplatform/vaadin/flow/i18n/LocalizationProvider.html[LocalizationProvider^] API is used by the UI components and builders to obtain the localization information and to localize the messages to display.

The `LocalizationProvider` API makes available a set of static methods to seamlessy integrate the messages localization in any part of the application, delegating the actual internationalization logic to the concrete localization provider, if available, which can be either a Holon Platform `LocalizationContext` or a Vaadin Flow `I18NProvider`.

The *actual localization service to use* is automatically detected with the following strategy:

* If a Vaadin Flow `I18NProvider` is available from current `VaadinService`, it is used for messages localization.
* Otherwise, a `LocalizationContext` is used if available as a _context_ resource.

This way, the `LocalizationProvider` API  `getLocalization` static methods can be used as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=localizationProvider1,indent=0]
----
<1> Get the localization for the given `Localizable` message using the given `Locale`
<2> Get the localization for the given `message.localization.code` message code using the given `Locale` and the default `Default message` message if the localization is not available

If the `Locale` is not explicitly provided, the `LocalizationProvider` API  `localize` static methods can be used and the *current Locale* is obtained with the following strategy:

* If a current `UI` is available and a `Locale` is configured for the `UI`, this one is used.
* If a `LocalizationContext` is available as a _context_ resource and it is localized, the `LocalizationContext` current `Locale` is used.
* If a Vaadin Flow `I18NProvider` is available from current `VaadinService`, the first provided `Locale` is used if available.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=localizationProvider2,indent=0]
----
<1> Get the current `Locale`, if available
<2> Get the localization for the given `Localizable` message using the current `Locale`
<3> Get the localization for the given `message.localization.code` message code using the current `Locale`: the default `Default message` message is returned if the message localization or the current `Locale` is not available

==== Use a LocalizationContext as I18NProvider

The Holon Platform `LocalizationContext` can be used as a standard Vaadin Flow `I18NProvider` through the link:{apidir}/com/holonplatform/vaadin/flow/i18n/LocalizationContextI18NProvider.html[LocalizationContextI18NProvider^] API.

TIP: See the link:holon-core.html#LocalizationContext[LocalizationContext^] documentation for information about the `LocalizationContext` configuration and use.

The `LocalizationContextI18NProvider` provides static methods to build a `I18NProvider` instance which uses a `LocalizationContext` as message localizations provider.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=i18nprovider1,indent=0]
----
<1> Set the messages localization source
<2> Set the initial `Locale`
<3> Create a `I18NProvider` instance using the `LocalizationContext` as message localization provider

A `LocalizationContextI18NProvider` which uses the current `LocalizationContext` (if available as a _context_ resource) can be obtained with the `create()` method:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleI18n.java[tag=i18nprovider2,indent=0]
----
<1> Create a `LocalizationContext`
<2> Put the `LocalizationContext` instance as a Vaadin Session attribute
<3> Create a `I18NProvider` instance which uses the current `LocalizationContext`

[[Components]]
=== Component builders and providers

The link:{apidir}/com/holonplatform/vaadin/flow/components/Components.html[Components^] API is *the main entry point* to build and configure the UI components.

It provides a complete set of methods to obtain _fluent_ builders to create and configure both standard Vaadin Flow components and the additional UI components provided by the Holon Platform Vaadin Flow module.

The `Components` API structure:

|===
|Sub-interface |Provides

|*[NONE]*
|A set of _configure(*)_ methods to setup existing standard component instances and a set of methods to obtain the _fluent_ builders for base Vaadin components, such as `Button` and standard layout components. See <<BaseBuilders>>.

|*dialog*
|Message and question dialogs builders. See <<Dialogs>>.

|*view*
|Builders for view components and forms. See <<View>>.

|*input*
|Builders input components and forms. See <<Input>>.

|*listing*
|Builders for grid type components to list data. See <<Listing>>.
|===

==== Component builders structure

Each component builder API is composed by a set of specific builders, each related to a specific feature of the component. The feature builders are independent from the specific UI component to build, thus providing a common API which makes component configuration simple and intuitive.

For example, the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasTextConfigurator.html[HasTextConfigurator^] represents a builder part for UI components which supports a _text_, and it is included in any builder for UI components with text support.

Similarly, the the link:{apidir}/com/holonplatform/vaadin/flow/components/builders/HasSizeConfigurator.html[HasSizeConfigurator^] API is included in component builders which supports the component _size_ configuration.

This ensures a consistent and common API to build and configure any UI component.

In the example below, the `HasTextConfigurator` and the `HasSizeConfigurator` are used in the same way to configure a _label_ and a _button_ component text and size:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=builders1,indent=0]
----
<1> Get a _label_ component builder
<2> Set the label text (using the `HasTextConfigurator` API)
<3> Set the label width (using the `HasSizeConfigurator` API)
<4> Get a _button_ component builder
<5> Set the button text (using the `HasTextConfigurator` API)
<6> Set the button width (using the `HasSizeConfigurator` API)

[[BaseBuilders]]
==== Base components builders

===== Button

The `Components.button()` method provides a standard Vaadin `Button` component builder, with localizable text support.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=button,indent=0]
----
<1> Get the `Button` builder
<2> Set the button text
<3> Set the button localizable text, providing a default text and a message localization code
<4> Set the button description
<5> Set the button width to 100%
<6> Add a CSS style class name
<7> Add a theme variant
<8> Set the button icon
<9> Automatically disables button when clicked
<10> Add a click event listener
<11> Shorter to directly create a `Button` providing the text and the click handler

The `Components.nativeButton()` builder can be used to build a `NativeButton` component.

===== Label

A _label_ component can be used to display a text, which can be *localizable*, and can be implemented using a set of tags. The default tag used by the `Components.label()` method is `DIV`.

TIP: See <<I18n>> for information about the UI components text localization.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=label1,indent=0]
----
<1> Get a label builder using a `Div` component
<2> Set the label text
<3> Set the label localizable text, providing a default text and a message localization code
<4> Set the label description
<5> Set the label width to 100%
<6> Add a CSS style class name

Other builders are available for the tags: `P`, `SPAN`, `H1`, `H2`, `H3`, `H4`, `H5`, `H6`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=label2,indent=0]
----
<1> Get a label builder using a `Paragraph` component
<2> Get a label builder using a `Span` component
<3> Get a label builder using a `H1` component
<4> Get a label builder using a `H2` component
<5> Get a label builder using a `H3` component
<6> Get a label builder using a `H4` component
<7> Get a label builder using a `H5` component
<8> Get a label builder using a `H6` component

===== Layouts

The Vaadin Flow base layouts can be created and configured using the following builders:

* *Vertical layout: * `Components.vl()`.
* *Horizontal layout: * `Components.hl()`.
* *Form layout: * `Components.formLayout()`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=layouts,indent=0]
----
<1> Get a `VerticalLayout` builder
<2> Enable spacing
<3> Enable margins
<4> Set the default component alignment
<5> Set the justify content mode
<6> Set width and height to 100%
<7> Add a CSS style class name 
<8> Add a Button component
<9> Add two label components
<10> Add a component and set its alignment 
<11> Get a `HorizontalLayout` builder 
<12> Add a component
<13> Add another component
<14> Set the flex grow ratio for the first component
<15> Get a `FormLayout` builder 
<16> Add a component
<17> Add a FormItem slot with a component and its label
<18> Set the responsive steps

===== Context menu

The `Components.contextMenu()` method can be used to configure a `ContextMenu` and bind it to a component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=ctxmenu,indent=0]
----
<1> Get a `ContextMenu` builder
<2> Add a menu item with a text and a click handler
<3> Add disabled a menu item with a localizable text
<4> Add a menu item using a component
<5> Add a menu open change listener
<6> Build the `ContextMenu` and bind it to the `myComponent` component

[[BaseConfigurators]]
==== Base components configurators

Besides the builders, the `Components` API provides a set of _configurator_ methods, which can be used to *configure existing UI components*. The available configurators acts on some base UI components: label, Button and layouts.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleComponents.java[tag=configurators,indent=0]
----
<1> Configure the `Button`, setting a localizable text
<2> Configure the `VerticalLayout`, disabling spacing and adding a component

[[Dialogs]]
=== Dialogs

The `Components.dialog` sub-interface provides a set of method to build and configure a Vaadin Flow `Dialog`. Three types of dialogs are available, as described below.

==== Message Dialog

A *message dialog* is a `Dialog` which can be used to display a simple message to the user.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog1,indent=0]
----
<1> Build a message `Dialog` with given message text
<2> Build a message `Dialog` with given localizable message text and open it
<3> Shorter to build and show a message `Dialog` with a localizable message text

==== Confirm Dialog

A *confirm dialog* is a `Dialog` which can be used to display a simple message to the user and provides a `OK` button at the bottom right position.

The `OK` button can be configured using the dialog builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog2,indent=0]
----
<1> Get a confirm `Dialog` builder
<2> Set the localizable dialog message
<3> Configure the confirm dialog OK button
<4> Build and open the dialog
<5> Shorter to build and show a confirm `Dialog` with a localizable message text

==== Question Dialog

A *question dialog* is a `Dialog` which can be used to ask a question to the user and handle the user answer. A `QuestionDialogCallback` function must be provided to handle the user answer.

Two buttons are displayed at the bottom right position, which by default represents the `yes` or `no` answers. The buttons can be configured using the dialog builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog3,indent=0]
----
<1> Get a question `Dialog` builder, providing the user answer callback
<2> Set the localizable dialog message
<3> Configure the _confirm_ dialog button
<4> Configure the _deny_ dialog button
<5> Build and open the dialog
<6> Shorter to build and show a question `Dialog` with a localizable message text

==== Dialog configuration options

All the dialog builders provides a set of common `Dialog` configuration options, including:

* Dialog size configuration
* Dialog style configuration
* Dialog closing mode configuration and open change listener

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog4,indent=0]
----
<1> Set the dialog width
<2> Set the dialog height
<3> Add a CSS style class name
<4> Disable closing when `ESC` pressed
<5> Enable closing when user clicks outside the dialog
<6> Add a open change listener

==== Adding components to the Dialog

The dialog builders allow to add custom components to the `Dialog` content. The components can be added in two positions:

* In the main dialog content: will be placed after the dialog message label, if any.
* In the dialog bottom toolbar: will be placed before the standard dialog buttons, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleDialog.java[tag=dialog5,indent=0]
----
<1> Add a label component in the dialog content area
<2> Add a button component in the dialog toolbar

[[Listing]]
=== List data in grids

TBD

[[View]]
=== View components and forms

TBD

[[Input]]
=== Input components and forms

TBD

[[PropertyRenderers]]
=== Property renderers for UI components

TBD

[[VaadinSessionScope]]
== Vaadin session scope

TBD

[[DeviceInfo]]
=== Device information

TBD




