[[Navigator]]
== Routing and navigation

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow-navigator</artifactId>
<version>{revnumber}</version>
----

The `holon-vaadin-flow-navigator` artifact provides URL query parameters marshalling and unmarshalling between URL representation and Java types using the `@QueryParameter` annotation and a `Navigator` API which can be used to handle the application UI _views_ routing

Furthermore, a complete support for view _authentication_ and _authorization_ is provided, using the Holon Platform core authentication APIs.

[[NavigationParameters]]
=== Navigation parameters handling

When the `holon-vaadin-flow-navigator` artifact is in classpath, the URL query parameters marshalling and unmarshalling for application _routes_ is automatically enabled and setted up at application bootstrap.

The URL query parameters value handling can thus be implemented using the link:{apidir}/com/holonplatform/vaadin/flow/navigator/annotations/QueryParameter.html[QueryParameter^] annotation on _routing target classes_ (i.e. UI component classes annotated with `@Route`) class *fields*.

NOTE: For information about the Vaadin Flow routing architecture, including the `@Route` annotation and route layouts, see the link:https://vaadin.com/docs/flow[Vaadin Flow documentation^].

When a routing target class field is annotated with `@QueryParameter`, *its value will be automatically setted using the corresponding URL query parameter value*, if available, just before the component is rendered in application UI. 

The `String` type URL query parameter value will be *converted to the required Java type* declared by the field type. See <<QueryParameterTypes>> for the Java types supported by default and <<AddQueryParameterType>> to extend the supported Java types.

By default, the URL query parameter name bound to a `@QueryParameter` field is equal to the *field name*.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation1.java[tag=route1,indent=0]
----
<1> The bound URL query parameter name is the field name, i.e. `parameter`. For example, when the route `some/path?parameter=1` is used, the `parameter` field value will be setted to the `1` Integer value.

The `value()` annotation attribute can be used to *declare the URL query parameter name* to which the field is bound, if you don't want to use the field name.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation2.java[tag=route1,indent=0]
----
<1> The URL query parameter name bound to the `parameter` field is `myparam`. For example, when the route `some/path?myparam=1` is used, the `parameter` field value will be setted to the `1` Integer value.

The routing target class field declaration (even `private`) it's enough to enable the the query parameter value handling, but the standard Java Beans convention can be also used, providing a *setter method* to set the field value.

If a field setter method is available in the routing target class, it will be used to set the query parameter field value. This allows, for example, to perform some operations one the query parameter value before it is setted as field value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation3.java[tag=route1,indent=0]
----
<1> The setter method will be used to set the `parameter` query parameter field value

[[UseParameterValues]]
==== Using the injected parameter values

The URL query paramter values are automatically injected in the routing target class `@QueryParameter` annotated fields at the _*after navigation*_ routing lifecycle event, i.e. when the routing target component instance is added to the UI.

For this reason, consistent parameter values are only available from this phase on. To handle and use the `@QueryParameter` annotated fields value, you have to ensure to be at least in the  _after navigation_ lifecycle phase of the routing component.

For this purpose, the `com.vaadin.flow.router.AfterNavigationObserver` interface can be used, implementing it by the routing target class.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation4.java[tag=route1,indent=0]
----
<1> Implement the `AfterNavigationObserver` interface to manage _after navigation_ events
<2> When the after navigation event occurs, all the `@QueryParameter` fields values are consistent and already injected using the URL query parameters

Since it is bound to the same _after navigation_ lifecycle phase, a `@OnShow` annotated method can also be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation5.java[tag=route1,indent=0]
----
<1> When a `@OnShow` annotated method in invoked, all the `@QueryParameter` fields values are consistent and already injected using the URL query parameters

See <<OnShow>> for details.

[[QueryParameterTypes]]
==== Built in query parameter types

By default, the following Java types are supported for query parameter values conversion from the URL query string:

|===
|Type |Sub type |Format

|*String*
|[NONE]
|Any text

|*Number*
|`Integer`, `Long`, `Short`, `Byte`, `Float`, `Double`, `BigInteger`, `BigDecimal`
|For decimal numbers, the *dot* (`.`) character must be used as decimal positions separator. The `-` character can be used for negative numbers. Hexadecimal representation is supported using the `0x` or `0X` prefix.

|*Boolean*
|[NONE]
|`true` or `false`

|*Enums*
|[NONE]
|The enumeration value *name*

|*LocalDate*
|[NONE]
|ISO date format, for example `2019-01-11`

|*LocalTime*
|[NONE]
|ISO time format, for example `10:15` or `10:15:30`

|*LocalDateTime*
|[NONE]
|ISO date and time format, for example `2019-01-11T10:15:30`

|*OffsetTime*
|[NONE]
|ISO time format with offset support, for example `10:15:30+01:00`

|*OffsetDateTime*
|[NONE]
|ISO date and time format with offset support, for example `2019-01-11T10:15:30+01:00` or `2019-01-11T10:15:30+01:00[Europe/Paris]`

|*java.util.Date*
|[NONE]
|ISO date and/or time format, for example `2019-01-11` or `2019-01-11T10:15:30`

|===

[[OptionalQueryParameter]]
==== Optional query parameter values

The `java.util.Optional` class is supported for `@QueryParameter` field type declarations.

Using `Optional`, the field value will never be `null`, and when the parameter value is not available a `Optional.empty()` value is setted as field value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation6.java[tag=route1,indent=0]
----
<1> `Optional` query parameter `String` type declaration

[[MultipleQueryParameter]]
==== Multiple query parameter values

Multiple query parameter values are supported either using the `java.util.Set` or `java.util.List` class.

For example, given the following routing target class:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation7.java[tag=route1,indent=0]
----
<1> Query parameter with multiple value support declaration using a `java.util.Set`

For the routing URL `some/path?parameter=a&parameter=b`, the `parameter` field value will be a `java.util.Set` instance containing the `a` and `b` String values.

When the URL query parameter value is not available, a empty `java.util.Set` or `java.util.List` is setted as field value.

[[AddQueryParameterType]]
==== Adding query parameter type support

The `@QueryParameter` annotated fields supported Java types set can be *extended*, adding support for new Java types marshalling and unmarshalling, using the link:{apidir}/com/holonplatform/vaadin/flow/navigator/NavigationParameterTypeMapper.html[NavigationParameterTypeMapper^] API.

To add support for a new query parameter type, a `NavigationParameterTypeMapper` instance bound to the required type can be created and automatically registered using the Java service extension architecture, i.e. providing a `com.holonplatform.vaadin.flow.navigator.NavigationParameterTypeMapper` named file in the `META-INF/services` folder of a jar, containing the `NavigationParameterTypeMapper` concrete class names to register.

For example, suppose we need to handle the following `MyType` parameter type:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation8.java[tag=type,indent=0]
----

We can create a new `NavigationParameterTypeMapper` class, generalized on the `MyType` type, as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation8.java[tag=mapper,indent=0]
----
<1> Handled parameter type declaration
<2> Parameter value unmarshalling to the `String` type URL query parameter value
<3> Parameter value marshalling from the `String` type URL query parameter value

An then register the `MyTypeParameterMapper` class using the Java service extension architecture, creating a suitable file under the `META-INF/services` folder:

.com.holonplatform.vaadin.flow.navigator.NavigationParameterTypeMapper file
[source, text]
----
my.package.MyTypeParameterMapper
----

This way, the `MyType` parameter type will be automatically handled using the `@QueryParameter` annotation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation8.java[tag=route,indent=0]
----
<1> The `MyType` type parameter is handled using the `MyTypeParameterMapper` class

[[RequiredQueryParameter]]
==== Required query parameters

The `required()` attribute of the `@QueryParameter` annotation can be used to declare *required* query parameter values.

When a required query parameter value is not available from the URL query string, a navigation error is fired before the navigation to the routing target occurs.

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/exceptions/InvalidNavigationParameterException.html[InvalidNavigationParameterException^] is used to notify the error and interrupt the navigation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation9.java[tag=route1,indent=0]
----
<1> The query parameter is required

See <<DefaultQueryParameter>> to provide a default value for a parameter, which can be used to provide a default value for a required parameter when it is not available from the URL query string.

[[DefaultQueryParameter]]
==== Default query parameter values

The `defaultValue()` attribute of the `@QueryParameter` annotation can be used to declare a *default value* for a query parameter. This value will be used and injected into the parameter field when the parameter value is not available from the URL query string.

The `defaultValue()` attribute value is a `String`, and the format conventions described in <<QueryParameterTypes>> should be used as `String` format for the supported Java types.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation10.java[tag=route1,indent=0]
----
<1> Declare the parameter default value

[[OnShow]]
=== Using `@OnShow` on route target classes

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/annotations/OnShow.html[OnShow^] annotation can be used un *route target class methods* to handle the _*after navigation*_ routing lifecycle event, i.e. to execute code when the routing target component instance is added to the UI.

A method annotation with `@OnShow`:

* Must be `public`.
* Can declare either no parameters or a single  parameter of type `com.vaadin.flow.router.AfterNavigationEvent`, to obtain the event which triggered the method invocation.

Any valid `@OnShow` annotated method (including super classes) in invoked at the _after navigation_ phase of the routing target component. No invocation order is guaranteed.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation11.java[tag=route1,indent=0]
----
<1> Declare the method to be invoked just after the navigation to this routing target
<2> Declare the method to be invoked just after the navigation to this routing target, providing the  `AfterNavigationEvent` type event

[[NavigatorAPI]]
=== The `Navigator` API

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/Navigator.html[Navigator^] API can be used to handle application routing.

TBD

[[NavigationLink]]
==== Navigation links

TBD

[[RouteAuthentication]]
=== Authentication support for UI routes

TBD

[[RouteAuthorization]]
=== Authorization support for UI routes

TBD


