[[Navigator]]
== Routing and navigation

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow-navigator</artifactId>
<version>{revnumber}</version>
----

The `holon-vaadin-flow-navigator` artifact provides URL query parameters marshalling and unmarshalling between URL representation and Java types using the `@QueryParameter` annotation and a `Navigator` API which can be used to handle the application UI _views_ routing

Furthermore, a complete support for view _authentication_ and _authorization_ is provided, using the Holon Platform core authentication APIs.

[[NavigationParameters]]
=== Navigation parameters handling

When the `holon-vaadin-flow-navigator` artifact is in classpath, the URL query parameters marshalling and unmarshalling for application _routes_ is automatically enabled and setted up at application bootstrap.

The URL query parameters value handling can thus be implemented using the link:{apidir}/com/holonplatform/vaadin/flow/navigator/annotations/QueryParameter.html[QueryParameter^] annotation on _routing target classes_ (i.e. UI component classes annotated with `@Route`) class *fields*.

NOTE: For information about the Vaadin Flow routing architecture, including the `@Route` annotation and route layouts, see the link:https://vaadin.com/docs/flow[Vaadin Flow documentation^].

When a routing target class field is annotated with `@QueryParameter`, *its value will be automatically setted using the corresponding URL query parameter value*, if available, just before the component is rendered in application UI. 

The `String` type URL query parameter value will be *converted to the required Java type* declared by the field type. See <<QueryParameterTypes>> for the Java types supported by default and <<AddQueryParameterType>> to extend the supported Java types.

By default, the URL query parameter name bound to a `@QueryParameter` field is equal to the *field name*.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation1.java[tag=route1,indent=0]
----
<1> The bound URL query parameter name is the field name, i.e. `parameter`. For example, when the route `some/path?parameter=1` is used, the `parameter` field value will be setted to the `1` Integer value.

The `value()` annotation attribute can be used to *declare the URL query parameter name* to which the field is bound, if you don't want to use the field name.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation2.java[tag=route1,indent=0]
----
<1> The URL query parameter name bound to the `parameter` field is `myparam`. For example, when the route `some/path?myparam=1` is used, the `parameter` field value will be setted to the `1` Integer value.

The routing target class field declaration (even `private`) it's enough to enable the the query parameter value handling, but the standard Java Beans convention can be also used, providing a *setter method* to set the field value.

If a field setter method is available in the routing target class, it will be used to set the query parameter field value. This allows, for example, to perform some operations one the query parameter value before it is setted as field value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation3.java[tag=route1,indent=0]
----
<1> The setter method will be used to set the `parameter` query parameter field value

[[ParameterURLEncodingDecoding]]
==== Query parameter URL encoding and decoding

By default, all the navigation related APIs automatically handle the query parameter names and values  *encoding*, when serialized to a URL, and *decoding*, when deserialized from a URL.

The query parameter names and values encoding and decoding is performed using the `application/x-www-form-urlencoded` MIME type and the default `UTF-8` charset.

Each API which handles URL query parameters provides method to skip the query parameter names and values encoding and decoding, if required.

See the specific API documentation below for further details.

[[UseParameterValues]]
==== Using the injected parameter values

The URL query paramter values are automatically injected in the routing target class `@QueryParameter` annotated fields at the _*after navigation*_ routing lifecycle event, i.e. when the routing target component instance is added to the UI.

For this reason, consistent parameter values are only available from this phase on. To handle and use the `@QueryParameter` annotated fields value, you have to ensure to be at least in the  _after navigation_ lifecycle phase of the routing component.

For this purpose, the `com.vaadin.flow.router.AfterNavigationObserver` interface can be used, implementing it by the routing target class.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation4.java[tag=route1,indent=0]
----
<1> Implement the `AfterNavigationObserver` interface to manage _after navigation_ events
<2> When the after navigation event occurs, all the `@QueryParameter` fields values are consistent and already injected using the URL query parameters

Since it is bound to the same _after navigation_ lifecycle phase, a `@OnShow` annotated method can also be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation5.java[tag=route1,indent=0]
----
<1> When a `@OnShow` annotated method in invoked, all the `@QueryParameter` fields values are consistent and already injected using the URL query parameters

See <<OnShow>> for details.

[[DirectParameterValuesDeserialization]]
==== Direct query parameter values deserialization

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/NavigationParameters.html[NavigationParameters^] API can be used to directly deserialize URL query parameter values into the supported Java types.

The `NavigationParameters` API provides a set of builder methods to create a `NavigationParameters` handler instance from a `Map` of query parameter name and values, from a `com.vaadin.flow.router.QueryParameters` instance or from a `com.vaadin.flow.router.Location` reference.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigationParameters.java[tag=np1,indent=0]
----
<1> Create a `NavigationParameters` from a `Map` of query parameter name and values
<2> Create a `NavigationParameters` from a `com.vaadin.flow.router.QueryParameters` instance
<3> Create a `NavigationParameters` from a `com.vaadin.flow.router.Location` reference

By default, the query parameter names and values are *decoded from the URL representation*, using the `application/x-www-form-urlencoded` MIME type and the default `UTF-8` charset.

To skip query parameter names and values decoding, the `NavigationParameters` API builder methods provides a `decode` parameter which can be set to `false`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigationParameters.java[tag=np2,indent=0]
----
<1> Set the `decode` parameter to `false` to skip the query parameter names and values decoding

The `NavigationParameters` API provides a set of methods to obtain the query parameter values, *deserialized to the required Java type*, if supported. 

TIP: See <<QueryParameterTypes>> for the Java types supported by default and <<AddQueryParameterType>> to extend the supported Java types.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigationParameters.java[tag=np3,indent=0]
----
<1> Create a `NavigationParameters` handler
<2> Check if a parameter named `myparam` is present and has a value
<3> Get the values of the parameter named `myparam`, deserialized using the `Integer` type
<4> Get the single value of the parameter named `myparam`, deserialized using the `Integer` type, if available
<5> Get the single value of the parameter named `myparam`, deserialized using the `Integer` type, or the default `0` value

[[QueryParameterTypes]]
==== Built in query parameter types

By default, the following Java types are supported for query parameter values conversion from the URL query string:

|===
|Type |Sub type |Format

|*String*
|[NONE]
|Any text

|*Number*
|`Integer`, `Long`, `Short`, `Byte`, `Float`, `Double`, `BigInteger`, `BigDecimal`
|For decimal numbers, the *dot* (`.`) character must be used as decimal positions separator. The `-` character can be used for negative numbers. Hexadecimal representation is supported using the `0x` or `0X` prefix.

|*Boolean*
|[NONE]
|`true` or `false`

|*Enums*
|[NONE]
|The enumeration value *name*

|*LocalDate*
|[NONE]
|ISO date format, for example `2019-01-11`

|*LocalTime*
|[NONE]
|ISO time format, for example `10:15` or `10:15:30`

|*LocalDateTime*
|[NONE]
|ISO date and time format, for example `2019-01-11T10:15:30`

|*OffsetTime*
|[NONE]
|ISO time format with offset support, for example `10:15:30+01:00`

|*OffsetDateTime*
|[NONE]
|ISO date and time format with offset support, for example `2019-01-11T10:15:30+01:00` or `2019-01-11T10:15:30+01:00[Europe/Paris]`

|*java.util.Date*
|[NONE]
|ISO date and/or time format, for example `2019-01-11` or `2019-01-11T10:15:30`

|===

[[OptionalQueryParameter]]
==== Optional query parameter values

The `java.util.Optional` class is supported for `@QueryParameter` field type declarations.

Using `Optional`, the field value will never be `null`, and when the parameter value is not available a `Optional.empty()` value is setted as field value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation6.java[tag=route1,indent=0]
----
<1> `Optional` query parameter `String` type declaration

[[MultipleQueryParameter]]
==== Multiple query parameter values

Multiple query parameter values are supported either using the `java.util.Set` or `java.util.List` class.

For example, given the following routing target class:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation7.java[tag=route1,indent=0]
----
<1> Query parameter with multiple value support declaration using a `java.util.Set`

For the routing URL `some/path?parameter=a&parameter=b`, the `parameter` field value will be a `java.util.Set` instance containing the `a` and `b` String values.

When the URL query parameter value is not available, a empty `java.util.Set` or `java.util.List` is setted as field value.

[[AddQueryParameterType]]
==== Adding query parameter type support

The `@QueryParameter` annotated fields supported Java types set can be *extended*, adding support for new Java types marshalling and unmarshalling, using the link:{apidir}/com/holonplatform/vaadin/flow/navigator/NavigationParameterTypeMapper.html[NavigationParameterTypeMapper^] API.

To add support for a new query parameter type, a `NavigationParameterTypeMapper` instance bound to the required type can be created and automatically registered using the Java service extension architecture, i.e. providing a `com.holonplatform.vaadin.flow.navigator.NavigationParameterTypeMapper` named file in the `META-INF/services` folder of a jar, containing the `NavigationParameterTypeMapper` concrete class names to register.

For example, suppose we need to handle the following `MyType` parameter type:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation8.java[tag=type,indent=0]
----

We can create a new `NavigationParameterTypeMapper` class, generalized on the `MyType` type, as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation8.java[tag=mapper,indent=0]
----
<1> Handled parameter type declaration
<2> Parameter value unmarshalling to the `String` type URL query parameter value
<3> Parameter value marshalling from the `String` type URL query parameter value

An then register the `MyTypeParameterMapper` class using the Java service extension architecture, creating a suitable file under the `META-INF/services` folder:

.com.holonplatform.vaadin.flow.navigator.NavigationParameterTypeMapper file
[source, text]
----
my.package.MyTypeParameterMapper
----

This way, the `MyType` parameter type will be automatically handled using the `@QueryParameter` annotation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation8.java[tag=route,indent=0]
----
<1> The `MyType` type parameter is handled using the `MyTypeParameterMapper` class

[[RequiredQueryParameter]]
==== Required query parameters

The `required()` attribute of the `@QueryParameter` annotation can be used to declare *required* query parameter values.

When a required query parameter value is not available from the URL query string, a navigation error is fired before the navigation to the routing target occurs.

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/exceptions/InvalidNavigationParameterException.html[InvalidNavigationParameterException^] is used to notify the error and interrupt the navigation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation9.java[tag=route1,indent=0]
----
<1> The query parameter is required

See <<DefaultQueryParameter>> to provide a default value for a parameter, which can be used to provide a default value for a required parameter when it is not available from the URL query string.

[[DefaultQueryParameter]]
==== Default query parameter values

The `defaultValue()` attribute of the `@QueryParameter` annotation can be used to declare a *default value* for a query parameter. This value will be used and injected into the parameter field when the parameter value is not available from the URL query string.

The `defaultValue()` attribute value is a `String`, and the format conventions described in <<QueryParameterTypes>> should be used as `String` format for the supported Java types.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation10.java[tag=route1,indent=0]
----
<1> Declare the parameter default value

[[OnShow]]
=== Using `@OnShow` on route target classes

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/annotations/OnShow.html[OnShow^] annotation can be used un *route target class methods* to handle the _*after navigation*_ routing lifecycle event, i.e. to execute code when the routing target component instance is added to the UI.

A method annotation with `@OnShow`:

* Must be `public`.
* Can declare either no parameters or a single  parameter of type `com.vaadin.flow.router.AfterNavigationEvent`, to obtain the event which triggered the method invocation.

Any valid `@OnShow` annotated method (including super classes) in invoked at the _after navigation_ phase of the routing target component. No invocation order is guaranteed.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation11.java[tag=route1,indent=0]
----
<1> Declare the method to be invoked just after the navigation to this routing target
<2> Declare the method to be invoked just after the navigation to this routing target, providing the  `AfterNavigationEvent` type event

[[NavigatorAPI]]
=== The `Navigator` API

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/Navigator.html[Navigator^] API can be used to handle the application routing, i.e. the navigation between the UI components which represent the application _views_.

Each `Navigator` is bound to a UI and the `Navigator` API for the current UI can be obtained using the `get()` static method. This method checks if a `Navigator` instance is available as a _context_ resource and if not uses an internal registry to obtain the instance bound to the current UI, creating a new instance if none was bound to the UI yet.

TIP: See the Holon Platform link:holon-core.html#Context[Context^] documentation for information about the context resources management.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation12.java[tag=navigator1,indent=0]
----
<1> Get the `Navigator` API for the current UI

A `Navigator` instance can also be directly created for a specific UI using the `create` static method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation12.java[tag=navigator2,indent=0]
----
<1> Create a `Navigator` for the given UI

The `Navigator` API makes available a set of methods to handle the routing between the application's declared route targets, ensuring a *consistent query parameters* management with Java types marshalling support (see <<NavigationParameters>>) and providing suitable *routing URL builders* using the supported Java types to provide the query parameters value.

See <<QueryParameterTypes>> to learn about the default supported Java types for query parameters declaration and <<AddQueryParameterType>> to learn how to add support for additional Java types.

NOTE: For information about the Vaadin Flow routing architecture, including the `@Route` annotation and route layouts, see the link:https://vaadin.com/docs/flow[Vaadin Flow documentation^].

The `Navigator` API provides a set of `navigateTo(...)` methods to perform navigation towards a routing target. The routing target URL can be declared either using:

* The *route path*, as declared using the `@Route` annotation.
* The *routing target class* reference.
* A full URL *location*, which includes the route path and the optional query part with the query parameters declaration.

Each `Navigator` API `navigateTo(...)` method provides multiple versions in order to:

* Specify the query parameter values, using a map of query parameter name and the corresponding value, provided as one of the *supported Java type object*. The `Navigator` API will take care of parameter value serialization to be used in the URL query part.

* Specify one or more *path parameter*, if the routing target class support them through the `com.vaadin.flow.router.HasUrlParameter` interface.

For example, supposing the following routing target class is registered in the application:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation12.java[tag=target,indent=0]
----
<1> Declares a single `Integer` type query parameter named `myparam`

The `Navigator` API can be used as follows to navigate to the routing target:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation12.java[tag=navigator3,indent=0]
----
<1> Get the `Navigator` for the current UI
<2> Navigate to the `View` component using the route path
<3> Navigate to the `View` component using the route path and specifying the `myparam` query parameter value
<4> Navigate to the `View` component using the component class
<5> Navigate to the `View` component using the component class and specifying the `myparam` query parameter value
<6> Navigate to the `View` component using the full location URL, including the route path and the query parameters

Supposing the `View` component declares a _path parameter_ using the `com.vaadin.flow.router.HasUrlParameter` interface:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation13.java[tag=target,indent=0]
----

The `Navigator` API can be used as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation13.java[tag=navigator1,indent=0]
----
<1> Get the `Navigator` for the current UI
<2> Navigate to the `View` component using the component class and providing the path parameter `value`
<3> Navigate to the `View` component using the component class and providing both the path parameter `value` and the `myparam` query parameter value

Furthermore, the `Navigator` API provides provides two convenience methods:

* `navigateToDefault()`: to navigate to the default route, i.e. the empty (`""`) route, if available.
* `navigateBack()`: to navigate back in the browser navigation history.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation14.java[tag=navigator1,indent=0]
----
<1> Navigate to the default route
<2> Navigate back in the browser navigation history

[[NavigationBuilder]]
==== The navigation builder API

The `Navigator` API provides a *navigation URL builder API*, available through the `navigation(...)` methods, which allows to declare a routing target URL and its parameters (both _query_ and _path_ parameter types) using a _fluent_ style builder and then either perform the actual navigation or obtain the complete  location URL.

The navigation builder API can be obtained either specifying the *route path* or the *routing target class* and provides methods to set the _path_ or _query_ parameters to use.

The query parameter values are provided using one of the *supported Java types*, the `Navigator` API will take care of parameter value serialization to be used in the URL query part.

The navigation is performed using the `navigate()` method.

To obtain the complete URL location and do not perform the actual navigation, the `asLocation()` or `asLocationURL()` methods can be used, which provide the navigation URL as a `com.vaadin.flow.router.Location` object or a `String` respectively.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation15.java[tag=navigator1,indent=0]
----
<1> Get the `Navigator` for the current UI
<2> Build a navigation using a route path
<3> Add a query parameter value
<4> Add multiple query parameter values
<5> Perform the navigation action
<6> Build a navigation using a route target class
<7> Set the path parameter value
<8> Perform the navigation action
<9> Get the complete navigation URL as a `com.vaadin.flow.router.Location` object
<10> Get the complete navigation URL as a `String`

By default, the query parameter names and values are *encoded to the URL representation*, using the `application/x-www-form-urlencoded` MIME type and the default `UTF-8` charset.

To skip the query parameter names and values encoding, the `encodeQueryParameters` builder method can be used:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation15.java[tag=navigator4,indent=0]
----
<1> Build a navigation using a route path
<2> Add a query parameter value
<3> Add multiple query parameter values
<4> Disable the query parameters URL encoding
<5> Perform the navigation action

[[NavigationTargetURL]]
==== Get the URL of a navigation target

The `Navigator` API provides a set of `getUrl(...)` convenince methods to obtain the registered URL for a navigation target class.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation15.java[tag=navigator2,indent=0]
----
<1> Get the `View` routing target class base URL
<2> Get the `View` routing target class URL with the provided path parameter value
<3> Get the `View` routing target class URL with the provided path parameter values

[[NavigationChangeListener]]
==== Listening to navigation changes

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/NavigationChangeListener.html[NavigationChangeListener^] listener interface can be use to listen to navigation target changes.

The navigation change event provides:

* The changed URL *location*.
* The changed *navigation target component* instance.

A `NavigationChangeListener` can be registered using the `Navigator` API `addNavigationChangeListener` method and it is invoked when a routing action is performed, i.e. when the current navigation target changes.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation15.java[tag=navigator3,indent=0]
----
<1> Get the `Navigator` for the current UI
<2> Register a `NavigationChangeListener`
<3> The new navigation location
<4> The new navigation target instance

[[NavigationLink]]
==== Navigation links

The link:{apidir}/com/holonplatform/vaadin/flow/navigator/NavigationLink.html[NavigationLink^] API represents a *navigation link component*, which handles navigation internally instead of loading a new page in the browser.

The `NavigationLink` API provides a builder API to configure the navigation target URL, either specifying a route path or a routing target class, and providing any _path_ or _query_ parameter value.

The query parameter values are provided using one of the *supported Java types*, the link implementation will take care of parameter value serialization to be used in the URL query part.

The `NavigationLink` API extends `HasComponent`, allowing to use it as a UI component through the `getComponent()` method. See <<HasComponent>>.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation16.java[tag=navigator1,indent=0]
----
<1> Build a `NavigationLink` using a route path
<2> Add a query parameter value
<3> Set the link text
<4> Build a `NavigationLink` using a routing target class
<5> Add a query parameter value
<6> Add a path parameter value
<7> Set the link text
<8> Add the link component to a layout

By default, the query parameter names and values are *encoded to the URL representation*, using the `application/x-www-form-urlencoded` MIME type and the default `UTF-8` charset.

To skip the query parameter names and values encoding, the `encodeQueryParameters` builder method can be used:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation16.java[tag=navigator2,indent=0]
----
<1> Build a `NavigationLink` using a route path
<2> Add a query parameter value
<3> Disable the query parameters URL encoding
<4> Set the link text

[[RouteAuthentication]]
=== Authentication support for UI routes

When the `holon-vaadin-flow-navigator` artifact is in classpath, the link:{coreapidir}/com/holonplatform/core/auth/annotations/Authenticate.html[Authenticate^] annotation can be used on routing target classes to provide *authentication support* to the routing infrastructure.

A routing target class annotated with `@Authenticate` is under authentication control: only authenticated users can access the corresponding route.

An link:{coreapidir}/com/holonplatform/core/auth/AuthContext.html[AuthContext^] definition is required in order to enable the authentication support and the `AuthContext` to use must be available as a _context_ resource, for example bound to the Vaddin session.

NOTE: See the Holon Platform link:holon-core.html#AuthContext[AuthContext^] documentation for information about the authentication context and the link:holon-core.html#Realm[Realm^] documentation for information about the authentication configuration.

The `redirectURI()` attribute of the `@Authenticate` annotation can be used to specify a *redirection URL* to use when a not authenticated request is performed against an authentication protected route.

When a redirect URI is not provided and the authentication is not available for an authentication protected route, a link:{apidir}/com/holonplatform/vaadin/flow/navigator/exceptions/UnauthorizedNavigationException.html[UnauthorizedNavigationException^] is used to notify the error and interrupt the navigation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation17.java[tag=auth1,indent=0]
----
<1> The `View1` routing target class, and so the `some/path` route path, can be accessed only by an authenticated user 
<2> The `View2` routing target class, and so the `some/path` route path, can be accessed only by an authenticated user and a `login` redirect URI is specified and will be used to redirect the user navigation when the authentication is not available

The `@Authenticate` annotation can be also used on a *routing layout class*: any routing target class child of the layout will inherit the `@Authenticate` annotation definition.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation17.java[tag=auth2,indent=0]
----
<1> The `@Authenticate` is declared on a `RouterLayout`: any child routing target class will inherit the authentication control declaration
<2> The `View` routing target class declares `MainLayout` as parent layout, so it will be under authentication control

[[RouteAuthorization]]
=== Authorization support for UI routes

When the `holon-vaadin-flow-navigator` artifact is in classpath, the `javax.annotation.security.RolesAllowed` and `javax.annotation.security.PermitAll` annotations can be used on routing target classes to perform a *role based authorization access control* on routing targets.

An link:{coreapidir}/com/holonplatform/core/auth/AuthContext.html[AuthContext^] definition is required in order to enable the authorization support and the `AuthContext` to use must be available as a _context_ resource, for example bound to the Vaddin session.

NOTE: See the Holon Platform link:holon-core.html#AuthContext[AuthContext^] documentation for information about the authentication context and the link:holon-core.html#Realm[Realm^] documentation for information about the authentication configuration.

The user roles check is performed using the current `Authentication` permissions, provided by the `AuthContext`.

NOTE: See the Holon Platform link:holon-core.html#RealmAuthorization[Authorization^] documentation for information about the permissions configuration and control.

When the `javax.annotation.security.RolesAllowed` annotation is used, *any of the specified role name* must be granted to the current authenticated user in order to allow the route access.

When the authorization control fails, a link:{apidir}/com/holonplatform/vaadin/flow/navigator/exceptions/ForbiddenNavigationException.html[ForbiddenNavigationException^] is used to notify the error and interrupt the navigation.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleNavigation18.java[tag=authz,indent=0]
----
<1> The `View` routing target class, and so the `some/path` route path, is under authorization control and can be accessed only if either the `ROLE1` or `ROLE2` role name is granted to the authenticated user 
