[[VaadinSpring]]
== Spring integration

The `holon-vaadin-flow-spring` artifact provides support and integration with the https://spring.io[Spring^] framework.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow-spring</artifactId>
<version>{revnumber}</version>
----

The `holon-vaadin-flow-spring` artifact includes the standard Vaadin Flow Spring integration support, declaring the `vaadin-spring` artifact as dependency. See the link:https://vaadin.com/docs/flow/spring/tutorial-spring-basic.html[Vaadin Spring documentation^] for information about the standard integration features and setup.

[[EnableNavigator]]
=== Provide the `Navigator` API as a Spring bean

The link:{apidir}/com/holonplatform/vaadin/flow/spring/EnableNavigator.html[EnableNavigator^] annotation can be used on a Spring configuration class to made available a UI-scoped `Navigator` instance as a Spring bean.

The Vaadin Spring *UI scope* must be enabled to use this configuration annotation, for example using the `com.vaadin.flow.spring.annotation.EnableVaadin` annotation or the Vaadin Spring Boot integration auto-configuration facilities.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/flow/examples/ExampleSpring1.java[tag=spring1,indent=0]
----
<1> Enable the `Navigator` API UI-scoped Spring bean configuration
<2> Obtain the `Navigator` API instance for current UI using injection

[[SpringSecurity]]
=== Using Spring Security for authorization control

The link:{apidir}/com/holonplatform/vaadin/flow/spring/EnableSecuredRoute.html[EnableSecuredRoute^] annotation can be used on a Spring configuration class to enable the Spring Security `org.springframework.security.access.annotation.Secured` annotation on routing target classes to perform a role based route authorization access control.

IMPORTANT: The Spring Security dependency must be explicitly provided by the project and must be available on classpath.

In order to use the `@Secured` annotation based authorization control, a `SecurityContext` must be available and properly configured.

When the `javax.annotation.security.RolesAllowed` annotation is used, *any of the specified role name* must be granted to the current authenticated user in order to allow the route access.

When the authorization control fails, a link:{apidir}/com/holonplatform/vaadin/flow/navigator/exceptions/ForbiddenNavigationException.html[ForbiddenNavigationException^] is used to notify the error and interrupt the navigation.

[[VaadinSpringBoot]]
== Spring Boot integration

The `holon-vaadin-flow-spring-boot` artifact provides integration with https://projects.spring.io/spring-boot[Spring Boot^], dealing with `Navigator` API and `LocalizationContext` integration auto configuration.

To enable the Spring Boot auto-configuration the following artifact must be included in your project dependencies:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow-spring-boot</artifactId>
<version>{revnumber}</version>
----

The `holon-vaadin-flow-spring-boot` artifact includes the standard Vaadin Flow Spring Boot integration, declaring the `vaadin-spring` artifact as dependency. See the link:https://vaadin.com/docs/flow/spring/tutorial-spring-basic.html[Vaadin Spring documentation^] for information about the standard integration features and setup.

[[NavigatorAutoConfiguration]]
=== `Navigator` API auto-configuration

The `Navigator` API auto configuration provides automatic setup of a *UI-scoped* `Navigator` bean, if a `Navigator` type bean is not already available in application context. See <<EnableNavigator>>.

[[LocalizationContextAutoConfiguration]]
=== `LocalizationContext` integration auto configuration

The `LocalizationContext` integration auto-configuration provides the following features:

*1. Localization context localization synchronization:* 

If a `LocalizationContext` type bean is available in context, and its scope is either *UI* (`vaadin-ui`) or *Session* (`session`) or *Vaadin session* (`vaadin-session`), when the `LocalizationContext` localization changes, the changed `Locale` is reflected to the current Vaadin UI or Vaadin session, according to bean scope.

This feature can be disabled setting the application configuration property `holon.vaadin.localization-context.reflect-locale` to `false`.

*2. Localization context initialization:*

If a `LocalizationContext` type bean is available in context, and its scope is either *UI* (`vaadin-ui`) or *Session* (`session`) or *Vaadin session* (`vaadin-session`), the initial `Locale` detected at session/UI initialization (according to bean scope) is setted to the `LocalizationContext` instance.

This feature can be disabled setting the application configuration property `holon.vaadin.localization-context.auto-init` to `false`.

*3. Localization context `I18NProvider` integration:*

If a `LocalizationContext` type bean is available in context, and a `I18NProvider` type bean is not available, the detected `LocalizationContext` is used as `I18NProvider` and registered as a Spring bean using the `LocalizationContextI18NProvider` API.

See <<I18NProvider>>.

This feature can be disabled setting the application configuration property `holon.vaadin.localization-context.i18nprovider` to `false`.

[[Starters]]
=== Spring Boot starters

The following _starter_ artifacts are available to provide a quick project configuration setup using Maven dependency system:

*1.* The *Vaadin Flow starter* provides the dependencies to the Vaadin Flow Spring Boot integration artifact `holon-vaadin-flow-spring-boot`, in addition to:

* The link:holon-core.html#SpringBoot[Holon Platform Core Module Spring Boot integration^] base starter (`holon-starter`).
* The Spring Boot `spring-boot-starter-web` starter, which includes the embedded *Tomcat* auto-configuration.

See the link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter[Spring Boot starters documentation^] for details on Spring Boot _starters_.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-starter-vaadin-flow</artifactId>
<version>{revnumber}</version>
----

*2.* The *Vaadin Flow starter using Undertow* provides the same dependencies as the previous starter, but uses *Undertow* instead of Tomcat as embedded servlet container.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-starter-vaadin-flow-undertow</artifactId>
<version>{revnumber}</version>
----
