= Holon Platform Vaadin Flow Module - Reference manual
:description: Holon platform Vaadin Flow module reference documentation. \
The Holon Vaadin Flow module represents the platform support for the Vaadin web applications platform (version 10+), focusing on the user interface components and data binding features.
:revnumber: {project-version}
:apidir: ../api/holon-vaadin-flow
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2019

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The *Vaadin Flow* module provides integration between the Holon Platform architecture and the link:https://vaadin.com/flow[Vaadin Flow^] web applications platform. 

The module main features are:

* A complete set of UI components _fluent_ builders, to make the UI development fast and easy.
* A full integration with the Holon Platform link:holon-core.html#Property[Property model^] and link:holon-core.html#Datastore[Datastore API^] for data bound UI components.
* A complete support for UI components and messages localization, using the Holon Platform link:holon-core.html#i18n[internationalization^] support.
* A convenient _navigation_ API to manage the UI _views_, with typed parameters support and components lifecycle management.
* Integration with the Holon Platform link:holon-core.html#Auth[authentication and authentication^] architecture.
* A complete integration with *Spring* and *Spring Boot*, with application auto-configuration facilities.

=== Sources and contributions

The Holon Platform *Vaadin* module source code is available from the GitHub repository link:https://github.com/holon-platform/holon-vaadin-flow[https://github.com/holon-platform/holon-vaadin-flow^].

See the repository `README` file for information about:

* The source code structure.
* How to build the module artifacts from sources.
* Where to find the code examples.
* How to contribute to the module development.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-flow-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.vaadin</groupId>
			<artifactId>holon-vaadin-flow-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

// Inclusions

include::_core.adoc[]

include::_navigator.adoc[]

include::_spring.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger name for the *Vaadin* module is `com.holonplatform.vaadin`.

== System requirements

=== Java

The Holon Platform Vaadin module requires https://www.java.com[Java^] *8* or higher.

=== Vaadin

The Holon Platform Vaadin module requires the https://vaadin.com/flow[Vaadin Flow^] platform version *12* or higher.
